// @ts-check
// Extracted from App.jsx — all app-wide constants

export const SW = 640
export const SH = 480

export const STAGE_PRESETS = [
  // ── Digital Display ──────────────────────────────────────────
  { key: 'fhd_1920x1080',       cat: 'Digital Display', label: 'FHD 16∶9 — 1920 × 1080',            width: 1920, height: 1080 },
  { key: 'hd_1280x720',         cat: 'Digital Display', label: 'HD 16∶9 — 1280 × 720',              width: 1280, height: 720  },
  { key: 'uhd_3840x2160',       cat: 'Digital Display', label: '4K UHD — 3840 × 2160',              width: 3840, height: 2160 },
  { key: 'xga_1024x768',        cat: 'Digital Display', label: 'XGA 4∶3 — 1024 × 768',              width: 1024, height: 768  },
  { key: 'svga_800x600',        cat: 'Digital Display', label: 'SVGA 4∶3 — 800 × 600',              width: 800,  height: 600  },
  { key: 'vert_1080x1920',      cat: 'Digital Display', label: 'Vertical Portrait — 1080 × 1920',   width: 1080, height: 1920 },
  { key: 'legacy_640x480',      cat: 'Digital Display', label: 'Legacy VGA — 640 × 480',            width: 640,  height: 480  },
  // ── Social Media ─────────────────────────────────────────────
  { key: 'ig_sq_1080x1080',     cat: 'Social Media',    label: '📸 Instagram Square — 1080 × 1080', width: 1080, height: 1080 },
  { key: 'ig_story_1080x1920',  cat: 'Social Media',    label: '📸 Instagram Story / Reel — 1080 × 1920', width: 1080, height: 1920 },
  { key: 'ig_land_1080x608',    cat: 'Social Media',    label: '📸 Instagram Landscape — 1080 × 608',width: 1080, height: 608  },
  { key: 'fb_post_1200x630',    cat: 'Social Media',    label: 'f Facebook Post — 1200 × 630',      width: 1200, height: 630  },
  { key: 'tw_post_1200x675',    cat: 'Social Media',    label: '𝕏 Twitter/X Post — 1200 × 675',     width: 1200, height: 675  },
  { key: 'li_post_1200x627',    cat: 'Social Media',    label: 'in LinkedIn Post — 1200 × 627',     width: 1200, height: 627  },
  { key: 'yt_thumb_1280x720',   cat: 'Social Media',    label: '▶ YouTube Thumbnail — 1280 × 720',  width: 1280, height: 720  },
  { key: 'yt_banner_2560x1440', cat: 'Social Media',    label: '▶ YouTube Banner — 2560 × 1440',    width: 2560, height: 1440 },
  { key: 'tt_9x16_1080x1920',   cat: 'Social Media',    label: '♪ TikTok 9∶16 — 1080 × 1920',      width: 1080, height: 1920 },
  { key: 'pin_1000x1500',       cat: 'Social Media',    label: '📌 Pinterest Pin — 1000 × 1500',    width: 1000, height: 1500 },
  // ── Print ────────────────────────────────────────────────────
  { key: 'a4_port_794x1123',    cat: 'Print',           label: '🖨 A4 Portrait — 794 × 1123',        width: 794,  height: 1123 },
  { key: 'a4_land_1123x794',    cat: 'Print',           label: '🖨 A4 Landscape — 1123 × 794',       width: 1123, height: 794  },
  { key: 'a3_port_1123x1587',   cat: 'Print',           label: '🖨 A3 Portrait — 1123 × 1587',       width: 1123, height: 1587 },
  { key: 'a3_land_1587x1123',   cat: 'Print',           label: '🖨 A3 Landscape — 1587 × 1123',      width: 1587, height: 1123 },
  { key: 'us_let_816x1056',     cat: 'Print',           label: '🖨 US Letter Portrait — 816 × 1056', width: 816,  height: 1056 },
  { key: 'us_let_land_1056x816',cat: 'Print',           label: '🖨 US Letter Landscape — 1056 × 816',width: 1056, height: 816  },
  { key: 'bcard_1050x600',      cat: 'Print',           label: '🖨 Business Card — 1050 × 600',      width: 1050, height: 600  },
  { key: 'postcard_1012x638',   cat: 'Print',           label: '🖨 Postcard — 1012 × 638',           width: 1012, height: 638  },
  { key: 'rollup_800x2400',     cat: 'Print',           label: '🖨 Roll-up Banner — 800 × 2400',     width: 800,  height: 2400 },
  { key: 'banner_2400x800',     cat: 'Print',           label: '🖨 Wide Banner — 2400 × 800',        width: 2400, height: 800  },
  // ── Publishing / Storybook ───────────────────────────────────
  { key: 'book_a4_1684x1190',   cat: 'Publishing',      label: '📖 Book Spread A4 — 1684 × 1190',   width: 1684, height: 1190 },
  { key: 'book_lt_1700x1100',   cat: 'Publishing',      label: '📖 Book Spread Letter — 1700 × 1100',width: 1700, height: 1100 },
  { key: 'mag_dps_2480x1748',   cat: 'Publishing',      label: '📰 Magazine DPS A4 — 2480 × 1748',   width: 2480, height: 1748 },
  { key: 'ebook_1280x800',      cat: 'Publishing',      label: '📱 E-Book / Tablet — 1280 × 800',    width: 1280, height: 800  },
  // ── Square Book (8.5 × 8.5 in / 21.59 × 21.59 cm) — DPI variants ──────
  { key: 'sq_book_72dpi',       cat: 'Square Book',     label: '📐 Square Book 72 DPI — 612 × 612',      width: 612,  height: 612,  dpi: 72,  physicalCm: 21.59, aspect: '1:1' },
  { key: 'sq_book_96dpi',       cat: 'Square Book',     label: '📐 Square Book 96 DPI — 816 × 816',      width: 816,  height: 816,  dpi: 96,  physicalCm: 21.59, aspect: '1:1' },
  { key: 'sq_book_150dpi',      cat: 'Square Book',     label: '📐 Square Book 150 DPI — 1276 × 1276',   width: 1276, height: 1276, dpi: 150, physicalCm: 21.59, aspect: '1:1' },
  { key: 'sq_book_300dpi',      cat: 'Square Book',     label: '📐 Square Book 300 DPI — 2551 × 2551',   width: 2551, height: 2551, dpi: 300, physicalCm: 21.59, aspect: '1:1' },
  { key: 'sq_book_store_3000',  cat: 'Square Book',     label: '📐 Square Book eStore — 3000 × 3000',    width: 3000, height: 3000, dpi: 352, physicalCm: 21.59, aspect: '1:1' },
  { key: 'sq_book_store_3600',  cat: 'Square Book',     label: '📐 Square Book eStore HQ — 3600 × 3600', width: 3600, height: 3600, dpi: 423, physicalCm: 21.59, aspect: '1:1' },
  { key: 'sq_book_4k',          cat: 'Square Book',     label: '📐 Square Book 4K — 3840 × 3840',        width: 3840, height: 3840, dpi: 451, physicalCm: 21.59, aspect: '1:1' },
  // ── Custom (user-defined dimensions) ────────────────────────────────────
  { key: 'custom',              cat: 'Custom',          label: '✏️ Custom Size…',                         width: 640,  height: 480, custom: true },
]

/**
 * DPI options for the square-book picker — 21.59 × 21.59 cm (8.5 × 8.5 in).
 * Extend this array to add future resolution support without touching UI code.
 * @type {{ dpi: number, label: string, px: number }[]}
 */
export const SQUARE_BOOK_DPI_OPTIONS = [
  { dpi: 72,  label: '72 DPI — Web / Screen',           px: 612  },
  { dpi: 96,  label: '96 DPI — Standard Digital',       px: 816  },
  { dpi: 150, label: '150 DPI — High-quality Screen',   px: 1276 },
  { dpi: 300, label: '300 DPI — Print / Retina',        px: 2551 },
  { dpi: 352, label: 'eStore Recommended (3000 × 3000)',px: 3000 },
  { dpi: 423, label: 'eStore HQ (3600 × 3600)',         px: 3600 },
  { dpi: 451, label: '4K Square (3840 × 3840)',         px: 3840 },
]

export const WIPES = [
  'Fade',
  'PageFlip',
  'Wipe',
  'Straight',
  'ZoomUp',
  'ZoomInOut',
  'ZoomPush',
  'InYoFace',
  'SquareZoom',
  'GlideInOut',
  'GlideWave',
  'DropWave',
  'PaintRoller',
  'SqueezeIn',
  'RandomSquareZoom',
  'BlindsFantasy2',
  'BlindsFantasy3',
  'SmallBlinds',
  'ClosingBlinds',
  'BouncingBlinds',
  'SpiralIris',
  'Crescent',
  'Boomerang',
  'Damped',
  'Cascade',
  'Vortex',
  'Megalopolis',
  'Sine',
  'Stacker',
  'Stripes',
  'Stripper',
  'SuperStripper',
  'Wiper',
  'SoftDiagonal',
  'FlipFour',
  'FlipCoin',
  'CornerSlice',
  'TheBlob',
  'ReturnOfTheBlob',
  'WipeItOff',
  'Premiere',
  'PremiereReveal',
  'Swiss',
  'DiagonalZooms',
  'ScaleIn',
  'ScrollDivide',
  'SplitSweep',
  'Center',
  'ArcIn',
  'SwimIn',
  'Timeslice',
  'Texture',
  'SplineWave',
  'GlideIn',
  'RandomAlways',
  'RandomOnce',
  'CopyBackground',
]

export const BTN_SHAPES = [
  { key: 'rect',          label: '▬',  title: 'Rectangle',       radius: '0px' },
  { key: 'rounded',       label: '▢',  title: 'Rounded',         radius: '8px' },
  { key: 'pill',          label: '⬭',  title: 'Pill',            radius: '999px' },
  { key: 'ellipse',       label: '⬤',  title: 'Ellipse',         radius: '50%' },
  { key: 'triangle-u',    label: '▲',  title: 'Triangle Up',     radius: '0px', clipPath: 'polygon(50% 0%, 0% 100%, 100% 100%)',                                                                                                                                  textY: '68%' },
  { key: 'triangle-d',    label: '▼',  title: 'Triangle Down',   radius: '0px', clipPath: 'polygon(0% 0%, 100% 0%, 50% 100%)',                                                                                                                                   textY: '32%' },
  { key: 'triangle-l',    label: '◀',  title: 'Triangle Left',   radius: '0px', clipPath: 'polygon(0% 50%, 100% 0%, 100% 100%)',                                                                                                                                  textX: '66%' },
  { key: 'triangle-r',    label: '▶',  title: 'Triangle Right',  radius: '0px', clipPath: 'polygon(0% 0%, 100% 50%, 0% 100%)',                                                                                                                                   textX: '34%' },
  { key: 'diamond',       label: '◆',  title: 'Diamond',         radius: '0px', clipPath: 'polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%)' },
  { key: 'hexagon',       label: '⬡',  title: 'Hexagon',         radius: '0px', clipPath: 'polygon(25% 0%, 75% 0%, 100% 50%, 75% 100%, 25% 100%, 0% 50%)' },
  { key: 'pentagon',      label: '⬠',  title: 'Pentagon',        radius: '0px', clipPath: 'polygon(50% 0%, 100% 38%, 82% 100%, 18% 100%, 0% 38%)',                                                                                                               textY: '56%' },
  { key: 'octagon',       label: '⯃',  title: 'Octagon',         radius: '0px', clipPath: 'polygon(30% 0%, 70% 0%, 100% 30%, 100% 70%, 70% 100%, 30% 100%, 0% 70%, 0% 30%)' },
  { key: 'star-5',        label: '★',  title: '5-Point Star',    radius: '0px', clipPath: 'polygon(50% 0%,61% 35%,98% 35%,68% 57%,79% 91%,50% 70%,21% 91%,32% 57%,2% 35%,39% 35%)',                                                                           textY: '56%' },
  { key: 'star-6',        label: '✶',  title: '6-Point Star',    radius: '0px', clipPath: 'polygon(50% 0%,63% 25%,87% 6%,75% 31%,100% 38%,76% 50%,91% 75%,64% 62%,50% 88%,36% 62%,9% 75%,24% 50%,0% 38%,25% 31%,13% 6%,37% 25%)' },
  { key: 'arrow-r',       label: '➤',  title: 'Arrow Right',     radius: '0px', clipPath: 'polygon(0% 20%, 60% 20%, 60% 0%, 100% 50%, 60% 100%, 60% 80%, 0% 80%)',                                                                                              textX: '30%' },
  { key: 'arrow-l',       label: '◁',  title: 'Arrow Left',      radius: '0px', clipPath: 'polygon(40% 0%, 40% 20%, 100% 20%, 100% 80%, 40% 80%, 40% 100%, 0% 50%)',                                                                                            textX: '70%' },
  { key: 'cross',         label: '✚',  title: 'Cross/Plus',      radius: '0px', clipPath: 'polygon(33% 0%,67% 0%,67% 33%,100% 33%,100% 67%,67% 67%,67% 100%,33% 100%,33% 67%,0% 67%,0% 33%,33% 33%)' },
  { key: 'parallelogram', label: '▱',  title: 'Parallelogram',   radius: '0px', clipPath: 'polygon(15% 0%, 100% 0%, 85% 100%, 0% 100%)' },
  { key: 'trapezoid',     label: '⏢',  title: 'Trapezoid',       radius: '0px', clipPath: 'polygon(15% 0%, 85% 0%, 100% 100%, 0% 100%)' },
  { key: 'shield',        label: '🛡',  title: 'Shield',          radius: '0px', clipPath: 'polygon(50% 0%, 100% 20%, 100% 62%, 50% 100%, 0% 62%, 0% 20%)',                                                                                                     textY: '44%' },
  { key: 'custom-png',    label: '🖼',  title: 'Custom PNG Mask', radius: '0px' },
]

// ── Element animation definitions ────────────────────────────
export const ANIM_IN_TYPES = [
  { key: 'none',       label: '— None —',          css: '' },
  { key: 'fade',       label: '✨ Fade In',          css: 'smm-fade-in' },
  { key: 'fly-left',   label: '← Fly from Left',    css: 'smm-fly-left' },
  { key: 'fly-right',  label: '→ Fly from Right',   css: 'smm-fly-right' },
  { key: 'fly-top',    label: '↑ Fly from Top',     css: 'smm-fly-top' },
  { key: 'fly-bottom', label: '↓ Fly from Bottom',  css: 'smm-fly-bottom' },
  { key: 'zoom-in',    label: '🔍 Zoom In',          css: 'smm-zoom-in' },
  { key: 'zoom-big',   label: '🔎 Zoom from Big',   css: 'smm-zoom-big' },
  { key: 'spiral-in',  label: '🌀 Spiral In',        css: 'smm-spiral-in' },
  { key: 'bounce',     label: '🏀 Bounce In',        css: 'smm-bounce-in' },
  { key: 'flip-x',     label: '↕ Flip (3D Vertical)',  css: 'smm-flip-x' },
  { key: 'flip-y',     label: '↔ Flip (3D Horizontal)', css: 'smm-flip-y' },
  { key: 'rotate-in',  label: '🔄 Rotate In',        css: 'smm-rotate-in' },
  { key: 'drop-in',    label: '⬇ Drop + Bounce',    css: 'smm-drop-in' },
  { key: 'swipe-left', label: '← Swipe from Right', css: 'smm-swipe-left' },
  { key: 'swipe-right',label: '→ Swipe from Left',  css: 'smm-swipe-right' },
  { key: 'roll-left',  label: '↩ Roll from Right',  css: 'smm-roll-left' },
  { key: 'typewriter',          label: '⌨ Type-writer',             css: 'smm-typewriter' },
  { key: 'scroll-up-credits',   label: '🎬 Scroll Up (Credits)',     css: 'smm-scroll-up-credits' },
  { key: 'scroll-down-credits', label: '🎬 Scroll Down (Drop-in)',   css: 'smm-scroll-down-credits' },
]

export const ANIM_OUT_TYPES = [
  { key: 'none',        label: '— Stay on screen —',   css: '' },
  { key: 'fade',        label: '✨ Fade Out',            css: 'smm-fade-out' },
  { key: 'fly-left',    label: '← Fly to Left',        css: 'smm-fly-left-out' },
  { key: 'fly-right',   label: '→ Fly to Right',       css: 'smm-fly-right-out' },
  { key: 'fly-top',     label: '↑ Fly to Top',         css: 'smm-fly-top-out' },
  { key: 'fly-bottom',  label: '↓ Fly to Bottom',      css: 'smm-fly-bottom-out' },
  { key: 'zoom-out',    label: '🔍 Zoom Out',           css: 'smm-zoom-out' },
  { key: 'zoom-big',    label: '🔎 Zoom to Big',       css: 'smm-zoom-big-out' },
  { key: 'spiral-out',  label: '🌀 Spiral Out',         css: 'smm-spiral-out' },
  { key: 'flip-x',      label: '↕ Flip Out (3D Vert)', css: 'smm-flip-x-out' },
  { key: 'flip-y',      label: '↔ Flip Out (3D Horiz)',css: 'smm-flip-y-out' },
  { key: 'rotate-out',  label: '🔄 Rotate Out',         css: 'smm-rotate-out' },
  { key: 'dissolve',    label: '💨 Dissolve',           css: 'smm-fade-out' },
  { key: 'swipe-left',  label: '← Swipe to Left',     css: 'smm-swipe-left-out' },
  { key: 'swipe-right', label: '→ Swipe to Right',    css: 'smm-swipe-right-out' },
]

export const ANIM_LOOP_TYPES = [
  { key: 'none',          label: '— None —',              css: '' },
  { key: 'pulse',         label: '💓 Pulse',               css: 'smm-loop-pulse' },
  { key: 'zoom-pulse',    label: '🔍 Zoom Pulse',           css: 'smm-loop-zoom-pulse' },
  { key: 'float',         label: '🌊 Float / Bob',          css: 'smm-loop-float' },
  { key: 'shake',         label: '📳 Shake',                css: 'smm-loop-shake' },
  { key: 'wiggle',        label: '〰 Wiggle',               css: 'smm-loop-wiggle' },
  { key: 'spin',          label: '🔄 Spin',                 css: 'smm-loop-spin' },
  { key: 'neon-flicker',  label: '💡 Neon Flicker',         css: 'smm-loop-neon-flicker' },
  { key: 'color-cycle',   label: '🌈 Color Cycle',          css: 'smm-loop-color-cycle' },
  { key: 'glitch',        label: '⚡ Glitch',               css: 'smm-loop-glitch' },
  { key: 'breathe',       label: '🫧 Breathe (Opacity)',    css: 'smm-loop-breathe' },
  { key: 'marquee',       label: '📰 Marquee Scroll',       css: 'smm-loop-marquee' },
  { key: 'ken-burns',     label: '🎞 Ken Burns Zoom',        css: 'smm-loop-ken-burns' },
  { key: 'pendulum',      label: '⏱ Pendulum Swing',        css: 'smm-loop-pendulum' },
  { key: 'glow-pulse',    label: '✨ Glow Pulse',            css: 'smm-loop-glow-pulse' },
  { key: 'wave-sway',     label: '〰 Wave Sway',             css: 'smm-loop-wave-sway' },
  { key: 'zoom-drift',    label: '🔭 Zoom Drift',            css: 'smm-loop-zoom-drift' },
]

export const RETRO_BTN_PRESETS = [
  { key:'bevgrd',   label:'Bev Grad',  cat:'Beveled', bgGrad:'linear-gradient(180deg,#6090d0 0%,#2060a0 48%,#1050a0 100%)', fgColor:'#ffffff', borderColor:'#8ab0e0', borderWidth:2, radius:'4px', bevel:true,  textShadow:true  },
  { key:'bevpln',   label:'Bev Plain', cat:'Beveled', bgGrad:'linear-gradient(180deg,#3070b0 0%,#1a4a80 100%)',              fgColor:'#d0e8ff', borderColor:'#4a8fc0', borderWidth:2, radius:'4px', bevel:true,  textShadow:false },
  { key:'bevstr',   label:'Bev Strip', cat:'Beveled', bgGrad:'repeating-linear-gradient(90deg,#1a3a5c 0px,#1a3a5c 6px,#22507a 6px,#22507a 12px)', fgColor:'#e8e0c0', borderColor:'#4a8fc0', borderWidth:2, radius:'2px', bevel:true, textShadow:false },
  { key:'bevwav',   label:'Bev Wave',  cat:'Beveled', bgGrad:'linear-gradient(135deg,#3070b0 25%,#1a4080 50%,#3070b0 75%)', fgColor:'#ffffff', borderColor:'#6090d0', borderWidth:2, radius:'4px', bevel:true,  textShadow:false },
  { key:'metal',    label:'Metal',     cat:'Metal',   bgGrad:'linear-gradient(180deg,#d8d8d8 0%,#a0a0a0 48%,#808080 100%)', fgColor:'#202020', borderColor:'#606060', borderWidth:2, radius:'3px', bevel:true,  textShadow:false },
  { key:'crome1',   label:'Chrome 1',  cat:'Metal',   bgGrad:'linear-gradient(180deg,#f0f0f0 0%,#c0c0c0 30%,#787878 70%,#d0d0d0 100%)', fgColor:'#2a2a2a', borderColor:'#909090', borderWidth:1, radius:'4px', bevel:false, textShadow:false },
  { key:'crome2',   label:'Chrome 2',  cat:'Metal',   bgGrad:'linear-gradient(135deg,#fafafa 0%,#a0a0a0 50%,#f0f0f0 100%)', fgColor:'#1a1a1a', borderColor:'#808080', borderWidth:2, radius:'3px', bevel:true,  textShadow:false },
  { key:'alumbox',  label:'Alum Box',  cat:'Metal',   bgGrad:'linear-gradient(180deg,#c8d0e0 0%,#8090b8 50%,#c0c8d8 100%)', fgColor:'#1a2a3a', borderColor:'#5060a0', borderWidth:2, radius:'3px', bevel:true,  textShadow:false },
  { key:'wood',     label:'Wood',      cat:'Wood',    bgGrad:'linear-gradient(180deg,#a06030 0%,#7a4520 50%,#904828 100%)', fgColor:'#f0d090', borderColor:'#5a3010', borderWidth:2, radius:'3px', bevel:true,  textShadow:true  },
  { key:'wood2',    label:'Wood 2',    cat:'Wood',    bgGrad:'linear-gradient(180deg,#c08040 0%,#906020 50%,#b07030 100%)', fgColor:'#fff0c0', borderColor:'#704010', borderWidth:2, radius:'2px', bevel:true,  textShadow:true  },
  { key:'rock',     label:'Rock',      cat:'Stone',   bgGrad:'linear-gradient(180deg,#909090 0%,#606060 50%,#808080 100%)', fgColor:'#ffffff', borderColor:'#404040', borderWidth:2, radius:'2px', bevel:true,  textShadow:true  },
  { key:'slab',     label:'Slab',      cat:'Stone',   bgGrad:'linear-gradient(180deg,#b0b0b0 0%,#606060 100%)',              fgColor:'#ffffff', borderColor:'#303030', borderWidth:3, radius:'0px', bevel:true,  textShadow:true  },
  { key:'red-n',    label:'Red',       cat:'Neon',    bgGrad:'linear-gradient(180deg,#e04020 0%,#a01800 50%,#c02010 100%)', fgColor:'#ffffff', borderColor:'#e06040', borderWidth:2, radius:'4px', bevel:true,  textShadow:true  },
  { key:'red3d',    label:'Red 3D',    cat:'Neon',    bgGrad:'linear-gradient(180deg,#ff6060 0%,#cc0000 55%,#880000 100%)', fgColor:'#ffffff', borderColor:'#ff9090', borderWidth:2, radius:'6px', bevel:true,  textShadow:true  },
  { key:'blue-n',   label:'Blue',      cat:'Neon',    bgGrad:'linear-gradient(180deg,#4080e0 0%,#1040a0 50%,#2060c0 100%)', fgColor:'#ffffff', borderColor:'#60a0ff', borderWidth:2, radius:'4px', bevel:true,  textShadow:true  },
  { key:'blue3d',   label:'Blue 3D',   cat:'Neon',    bgGrad:'linear-gradient(180deg,#80d0ff 0%,#0090e0 55%,#0060c0 100%)', fgColor:'#ffffff', borderColor:'#90e0ff', borderWidth:2, radius:'6px', bevel:true,  textShadow:true  },
  { key:'yellow-n', label:'Yellow',    cat:'Neon',    bgGrad:'linear-gradient(180deg,#f0c040 0%,#c09010 50%,#e0a820 100%)', fgColor:'#3a2000', borderColor:'#f0d060', borderWidth:2, radius:'4px', bevel:true,  textShadow:false },
  { key:'green-n',  label:'Green',     cat:'Neon',    bgGrad:'linear-gradient(180deg,#40c040 0%,#108010 50%,#20a020 100%)', fgColor:'#ffffff', borderColor:'#60e060', borderWidth:2, radius:'4px', bevel:true,  textShadow:true  },
  { key:'purple',   label:'Purple',    cat:'Neon',    bgGrad:'linear-gradient(180deg,#8060d0 0%,#5030a0 50%,#6040b0 100%)', fgColor:'#ffffff', borderColor:'#a080e0', borderWidth:2, radius:'4px', bevel:true,  textShadow:true  },
  { key:'fire',     label:'Fire',      cat:'Special', bgGrad:'linear-gradient(180deg,#ff9020 0%,#e02000 55%,#ff4000 100%)', fgColor:'#ffff80', borderColor:'#ff6000', borderWidth:2, radius:'3px', bevel:false, textShadow:true  },
  { key:'cheese',   label:'Cheese',    cat:'Special', bgGrad:'linear-gradient(135deg,#f8e070 0%,#d0b020 50%,#e8c840 100%)', fgColor:'#3a2000', borderColor:'#b08000', borderWidth:3, radius:'8px', bevel:true,  textShadow:false },
  { key:'balloon',  label:'Balloon',   cat:'Special', bgGrad:'radial-gradient(ellipse at 35% 35%,#90d0ff,#1060c0)',         fgColor:'#ffffff', borderColor:'#4090e0', borderWidth:2, radius:'50%', bevel:false, textShadow:true  },
  { key:'sketch',   label:'Sketch',    cat:'Special', bgGrad:'linear-gradient(180deg,#f8f8f0 0%,#e0e0d8 100%)',             fgColor:'#333333', borderColor:'#606050', borderWidth:2, radius:'2px', bevel:false, textShadow:false },
  { key:'chalk',    label:'Chalk',     cat:'Special', bgGrad:'',                                                           bgColor:'#1a1a1a', fgColor:'#f0f0e0', borderColor:'#888880', borderWidth:1, radius:'2px', bevel:false, textShadow:false },
  { key:'post',     label:'Post',      cat:'Special', bgGrad:'linear-gradient(180deg,#f8f0d0 0%,#e8d8a0 100%)',             fgColor:'#3a2800', borderColor:'#c0a060', borderWidth:2, radius:'0px', bevel:false, textShadow:false },
  { key:'plain1',   label:'Dark',      cat:'Basic',   bgGrad:'',                                                           bgColor:'#1a3a5c', fgColor:'#e8a020', borderColor:'#4a8fc0', borderWidth:2, radius:'0px', bevel:false, textShadow:false },
  { key:'plain2',   label:'Grey',      cat:'Basic',   bgGrad:'',                                                           bgColor:'#2a2a2a', fgColor:'#c0c0c0', borderColor:'#606060', borderWidth:2, radius:'4px', bevel:false, textShadow:false },
  { key:'rounded',  label:'Rounded',   cat:'Basic',   bgGrad:'linear-gradient(180deg,#506080 0%,#304060 100%)',             fgColor:'#c0e0ff', borderColor:'#6080a0', borderWidth:2, radius:'12px',bevel:true,  textShadow:false },
]

export const BTN_ACTIONS = [
  { value: 'next',        label: 'Next Page' },
  { value: 'prev',        label: 'Previous Page' },
  { value: 'goto',        label: 'Go to Page' },
  { value: 'goto-if',     label: 'Go to Page (If Variable)' },
  { value: 'url',         label: 'Open URL / Hyperlink' },
  { value: 'play-media',  label: 'Play Media on Click' },
  { value: 'event',       label: 'Audio Event' },
  { value: 'set-var',     label: 'Set Script Variable' },
  { value: 'script',      label: 'Script' },
  { value: 'quit',        label: 'Quit / End' },
]

export const FONT_LIST = [
  // ── Google / Web Fonts ───────────────────────────────────────────────────────
  { group: 'Display & Headlines',  fonts: ['Rajdhani','Bebas Neue','Oswald','Anton','Orbitron','Exo 2','Russo One','Teko','Alfa Slab One','Black Ops One'] },
  { group: 'Sans Serif',           fonts: ['Open Sans','Roboto','Montserrat','Lato','Nunito','Poppins','Ubuntu','Titillium Web','Josefin Sans','Quicksand','Source Sans 3','Barlow'] },
  { group: 'Serif',                fonts: ['Playfair Display','Merriweather','PT Serif','Libre Baskerville','Lora','EB Garamond'] },
  { group: 'Monospace',            fonts: ['IBM Plex Mono','Source Code Pro','Share Tech Mono','VT323','Courier New'] },
  { group: 'Decorative & Fun',     fonts: ['Dancing Script','Pacifico','Righteous','Permanent Marker','Fredoka One','Baloo 2','Lobster','Comfortaa','Press Start 2P','Boogaloo'] },
  // ── Windows System Fonts ─────────────────────────────────────────────────────
  { group: 'Windows — Display & Decorative', fonts: ['Academy Engraved LET Plain','Algerian','Bauhaus 93','Bernard MT','Blackadder ITC','Blackletter 686 BT','Bodoni MT Poster Compressed','Broadway','Broadway BT','Castellar','Chiller','Colonna MT','Cooper','Copperplate Gothic','Curlz MT','Engravers MT','EngraversGothic BT','Eras','Eras Demi ITC','EthnocentricRg-Regular','Felix Titling','Footlight MT','Forte','Gabriola','Gloucester MT Extra','Goudy Stout','Harlow Solid','Harrington','Imprint MT Shadow','Jokerman','Juice ITC','Magneto','Maiandra GD','Mister Earl BT','Modern','Modern No. 20','Niagara Engraved','Niagara Solid','Old Dreadful No.7 BT','Old English Text MT','Onyx','Papyrus','Playbill','Pump Demi','Ravie','Showcard Gothic','Snap ITC','Stencil','Tempus Sans ITC','Wide Latin'] },
  { group: 'Windows — Sans Serif',           fonts: ['Agency FB','Arial','Arial Rounded MT','Arimo','Bahnschrift','Berlin Sans FB','Berlin Sans FB Demi','Calibri','Candara','Century Gothic','Century725 Cn BT','Corbel','DejaVu Sans','Dubai','Franklin Gothic','Franklin Gothic Book','Franklin Gothic Demi','Franklin Gothic Demi Cond','Futura Bk BT Book','Futura Md BT','GeoSlab703 Md BT','Geometr212 BkCn BT','Geometr415 Blk BT','Gill Sans MT','Gill Sans MT Ext','Gill Sans Ultra','Haettenschweiler','Humanst521 BT','Humanst521 Lt BT','Humnst777 BT Roman','Humnst777 Blk BT','Humnst777 Cn BT','Humnst777 Lt BT','Impact','Ink Free','Microsoft Sans Serif','NewsGoth BT','NewsGoth Cn BT','NewsGoth Lt BT','Segoe UI','Segoe UI Semibold','Segoe UI Semilight','Square721 BT','Square721 Cn BT','Swis721 BT','Swis721 Blk BT','Swis721 Cn BT','Swis721 Hv BT','Swis721 Lt BT','Swis721 LtEx BT','Tahoma','Trebuchet MS','Tw Cen MT','Verdana'] },
  { group: 'Windows — Serif',                fonts: ['Baskerville Old Face','Bell MT','Bodoni Bd BT','Bodoni Bk BT Book','Bodoni MT','Book Antiqua','Bookman Old Style','Californian FB','Calisto MT','Cambria','Centaur','Century','Century Schoolbook','Century751 BT','CentSchbkCyrill BT','Clarendon BT','Clarendon Blk BT','Clarendon Lt BT','Constantia','DeVinne Txt BT','DejaVu Serif','Elephant','Garamond','Gentium Basic','Gentium Book Basic','Georgia','Goudy Old Style','High Tower Text','Lucida Bright','News701 BT','News706 BT','Palatino Linotype','Perpetua','Perpetua Titling MT','Poor Richard','Rockwell','Rockwell Extra','Roman','Schadow BT','Sitka Small','Sylfaen','Times New Roman'] },
  { group: 'Windows — Monospace',            fonts: ['Consolas','DejaVu Sans Mono','Lucida Console','Lucida Sans Typewriter','OCR A Extended','OCR-A BT','OCR-B 10 BT'] },
  { group: 'Windows — Script & Calligraphy', fonts: ['Brush Script MT','Calligraphic 421 BT','Cataneo BT','Edwardian Script ITC','Embassy BT','Freehand521 BT','Freestyle Script','French Script MT','Gigi','Informal Roman','Kaufmann BT','Kunstler Script','Lucida Calligraphy','Lucida Handwriting','Matura MT Script Capitals','Mistral','Monotype Corsiva','One Stroke Script LET Plain','Palace Script MT','Parchment','Park Avenue BT','Pristina','Rage','Script MT','Segoe Script','Staccato 222 BT','Vivaldi','Vladimir Script'] },
  { group: 'Windows — Handwriting & Informal', fonts: ['Bradley Hand ITC','Comic Sans MS','Highlight LET Plain','John Handy LET Plain','Kristen ITC','La Bamba LET Plain','Mekanik LET Plain','Milano LET','Odessa LET Plain','Orange LET Plain','Quixley LET Plain','Ruach LET Plain','Scruff LET Plain','Segoe Print','Smudger LET Plain','Tiranti Solid LET Plain','University Roman LET Plain','Victorian LET Plain','Viner Hand ITC','Westwood LET Plain'] },
  { group: 'Windows — Other',                 fonts: ['Britannic','Exotc350 Bd BT','Lucida Sans','Lucida Sans Unicode','Yu Gothic'] },
]

export const PROJECT_TEMPLATES = [
  { id:'blank',           cat:'General',               icon:'📄', label:'Blank Project',           desc:'Start from scratch with a single empty page.',                                 preset:'legacy_640x480', wipeIn:'Fade'    },
  { id:'signage-hd',      cat:'Digital Signage',        icon:'📺', label:'HD Signage Loop',          desc:'Full HD 16∶9 looping display — ideal for screens and advertising.',           preset:'fhd_1920x1080',  wipeIn:'Fade'    },
  { id:'video-wall',      cat:'Digital Signage',        icon:'🎬', label:'Video Showcase',           desc:'Full-screen video player with overlay title and caption text.',                preset:'fhd_1920x1080',  wipeIn:'Fade'    },
  { id:'info-kiosk',      cat:'Interactive Kiosk',      icon:'🖥',  label:'Info Touch Kiosk',         desc:'Touch-screen home menu with navigation buttons to content sections.',          preset:'xga_1024x768',   wipeIn:'ZoomUp'  },
  { id:'product-kiosk',   cat:'Interactive Kiosk',      icon:'🛒', label:'Product / Menu Catalogue', desc:'Showcase products or menu items with interactive navigation and detail pages.',preset:'xga_1024x768',   wipeIn:'ZoomUp'  },
  { id:'storybook',       cat:'Interactive Publishing', icon:'📖', label:"Children's Storybook",     desc:'Double-page spread storybook with narration, tap-to-reveal and animations. Import PDF or build from scratch.',  preset:'book_a4_1684x1190', wipeIn:'PageFlip' },
  { id:'magazine',        cat:'Interactive Publishing', icon:'📰', label:'Digital Magazine',          desc:'Rich-media interactive publication with wipe transitions and article pages.',  preset:'fhd_1920x1080',  wipeIn:'Wipe'    },
  { id:'presentation',    cat:'Presentation',           icon:'📊', label:'Corporate Slideshow',       desc:'Timed auto-advancing slides for meetings, exhibitions and conferences.',        preset:'fhd_1920x1080',  wipeIn:'Fade'    },
  { id:'photo-slideshow', cat:'Presentation',           icon:'🖼', label:'Photo Slideshow',           desc:'Auto-advancing photo gallery with smooth crossfade transitions.',               preset:'fhd_1920x1080',  wipeIn:'Fade'    },
  { id:'quiz',            cat:'Educational',            icon:'✅', label:'Quiz / Test',               desc:'Multiple-choice quiz with correct and incorrect answer feedback pages.',        preset:'xga_1024x768',   wipeIn:'ZoomUp'  },
  { id:'puzzle',          cat:'Educational',            icon:'🧩', label:'Interactive Puzzle',        desc:'Activity-based matching or puzzle exercise with reveal pages.',                 preset:'xga_1024x768',   wipeIn:'ZoomUp'  },
  { id:'maze-game',       cat:'Educational',            icon:'🧭', label:'Maze Game',                 desc:'Editable multi-level maze adventure with character choice, scoring and winner page.', preset:'xga_1024x768', wipeIn:'ZoomUp'  },
  { id:'lesson',          cat:'Educational',            icon:'🎓', label:'Lesson / Tutorial',         desc:'Step-through educational lesson with checkpoint navigation buttons.',           preset:'xga_1024x768',   wipeIn:'Fade'    },
  { id:'memory-game',     cat:'Educational',            icon:'🧠', label:'Memory Game',              desc:'Classic card-flip memory matching game — find all 8 symbol pairs in the fewest flips', preset:'legacy_640x480', wipeIn:'Fade'    },
]

// Maps WIPE name → { icon, desc, animClass }
export const WIPE_META = {
  Fade:              { icon: '◑', desc: 'Cross-fade dissolve' },
  Wipe:              { icon: '▶▌', desc: 'Hard wipe right' },
  Straight:          { icon: '━', desc: 'Straight cut' },
  ZoomUp:            { icon: '⬆⊕', desc: 'Zoom up' },
  ZoomInOut:         { icon: '⊕⊖', desc: 'Zoom in then out' },
  ZoomPush:          { icon: '⊕▶', desc: 'Zoom push' },
  InYoFace:          { icon: '⊕!', desc: 'Aggressive zoom in' },
  SquareZoom:        { icon: '⬚⊕', desc: 'Square zoom' },
  GlideInOut:        { icon: '⟿', desc: 'Smooth glide' },
  GlideWave:         { icon: '〜⟿', desc: 'Wavy glide' },
  DropWave:          { icon: '⬇〜', desc: 'Drop wave' },
  PaintRoller:       { icon: '🖌', desc: 'Paint roller sweep' },
  SqueezeIn:         { icon: '◁▷', desc: 'Squeeze in from sides' },
  RandomSquareZoom:  { icon: '⬚?', desc: 'Random square zooms' },
  BlindsFantasy2:    { icon: '≡2', desc: 'Blinds (2 strips)' },
  BlindsFantasy3:    { icon: '≡3', desc: 'Blinds (3 strips)' },
  SmallBlinds:       { icon: '≣', desc: 'Small horizontal blinds' },
  ClosingBlinds:     { icon: '⊟', desc: 'Closing blinds' },
  BouncingBlinds:    { icon: '⤧', desc: 'Bouncing blinds' },
  SpiralIris:        { icon: '🌀', desc: 'Spiral iris open' },
  Crescent:          { icon: '☽', desc: 'Crescent wipe' },
  Boomerang:         { icon: '↩', desc: 'Boomerang sweep' },
  Damped:            { icon: '〜↘', desc: 'Damped oscillation' },
  Cascade:           { icon: '⋱', desc: 'Cascade / waterfall' },
  Vortex:            { icon: '🌀▶', desc: 'Vortex spin' },
  Megalopolis:       { icon: '🏙', desc: 'City-block grid' },
  Sine:              { icon: '∿', desc: 'Sine wave wipe' },
  Stacker:           { icon: '⬓', desc: 'Stacked slide' },
  Stripes:           { icon: '▐▌', desc: 'Vertical stripes' },
  Stripper:          { icon: '▐▌▶', desc: 'Stripes peel' },
  SuperStripper:     { icon: '▐▐▌', desc: 'Wide stripes peel' },
  Wiper:             { icon: '⌒▶', desc: 'Windshield wiper' },
  SoftDiagonal:      { icon: '╱', desc: 'Soft diagonal wipe' },
  FlipFour:          { icon: '⊞', desc: 'Flip four panels' },
  FlipCoin:          { icon: '⏺', desc: 'Coin flip' },
  CornerSlice:       { icon: '◿', desc: 'Corner slice' },
  TheBlob:           { icon: '◉', desc: 'Organic blob' },
  ReturnOfTheBlob:   { icon: '◉↩', desc: 'Blob returns' },
  WipeItOff:         { icon: '✗▶', desc: 'Wipe it off' },
  Premiere:          { icon: '▶▐', desc: 'Premiere reveal left' },
  PremiereReveal:    { icon: '◀▐', desc: 'Premiere reveal right' },
  Swiss:             { icon: '✛', desc: 'Swiss cross open' },
  DiagonalZooms:     { icon: '╲⊕', desc: 'Diagonal zoom panels' },
  ScaleIn:           { icon: '⊡', desc: 'Scale in from centre' },
  ScrollDivide:      { icon: '⬆⬇', desc: 'Scroll split up/down' },
  SplitSweep:        { icon: '⬅▶', desc: 'Split sweep outward' },
  Center:            { icon: '⊕', desc: 'Iris from centre' },
  ArcIn:             { icon: '⌒', desc: 'Arc swing in' },
  SwimIn:            { icon: '〜⬆', desc: 'Swim in wavy' },
  Timeslice:         { icon: '⧗▶', desc: 'Time-sliced planes' },
  Texture:           { icon: '⠿', desc: 'Texture dissolve' },
  SplineWave:        { icon: '∿⬆', desc: 'Spline wave slide' },
  GlideIn:           { icon: '⟿⬆', desc: 'Glide in from bottom' },
  RandomAlways:      { icon: '?', desc: 'Random (always changes)' },
  RandomOnce:        { icon: '?¹', desc: 'Random (fixed per session)' },
  CopyBackground:    { icon: '⊡', desc: 'Copy background reveal' },
}

// Wipe/transition categories for FluxAura Studio
export const WIPE_CATEGORIES = [
  { key: 'all',     label: 'All',     wipes: null },
  { key: 'anim',    label: '🎬 Animate', wipes: null, isAnim: true },
  { key: 'fades',   label: '◑ Fades',   wipes: ['Fade','Texture','CopyBackground','Straight'] },
  { key: 'zooms',   label: '⊕ Zooms',   wipes: ['ZoomUp','ZoomInOut','ZoomPush','InYoFace','SquareZoom','ScaleIn','DiagonalZooms','Center'] },
  { key: 'wipes',   label: '▶ Wipes',   wipes: ['Wipe','Premiere','PremiereReveal','WipeItOff','SoftDiagonal','CornerSlice','Swiss','Crescent','Wiper','Boomerang'] },
  { key: 'pushes',  label: '⟿ Pushes',  wipes: ['GlideInOut','GlideIn','GlideWave','DropWave','SplitSweep','ScrollDivide','Stacker','SwimIn','SplineWave','ArcIn','SqueezeIn','Damped'] },
  { key: 'blinds',  label: '≡ Blinds',  wipes: ['BlindsFantasy2','BlindsFantasy3','SmallBlinds','ClosingBlinds','BouncingBlinds','Stripes','Stripper','SuperStripper'] },
  { key: 'dynamic', label: '🌀 Dynamic', wipes: ['SpiralIris','Vortex','Cascade','Megalopolis','Sine','FlipFour','FlipCoin','TheBlob','ReturnOfTheBlob','Timeslice','PaintRoller','RandomSquareZoom','ZoomPush'] },
  { key: 'random',  label: '? Random',  wipes: ['RandomAlways','RandomOnce'] },
]

// Fly-in entry animation meta for element wipe
export const FLYIN_META = [
  { value: '',           icon: '✕',   desc: 'None / No animation' },
  { value: 'fade',       icon: '◑',   desc: 'Fade in' },
  { value: 'wipe_right', icon: '▶▌',  desc: 'Wipe from left → right' },
  { value: 'wipe_left',  icon: '◀▌',  desc: 'Wipe from right → left' },
  { value: 'wipe_up',    icon: '▲▌',  desc: 'Wipe from bottom up' },
  { value: 'wipe_down',  icon: '▼▌',  desc: 'Wipe from top down' },
  { value: 'slide_right',icon: '▶⬜',  desc: 'Slide in from left' },
  { value: 'slide_left', icon: '◀⬜',  desc: 'Slide in from right' },
  { value: 'slide_up',   icon: '▲⬜',  desc: 'Slide in from bottom' },
  { value: 'slide_down', icon: '▼⬜',  desc: 'Slide in from top' },
  { value: 'zoom_in',    icon: '⊕',   desc: 'Zoom in from centre' },
  { value: 'iris',       icon: '◎',   desc: 'Iris/circle open' },
  { value: 'bounce',     icon: '⤵',   desc: 'Bounce in from bottom' },
  { value: 'flip_h',     icon: '↔',   desc: 'Flip in horizontally' },
  { value: 'flip_v',     icon: '↕',   desc: 'Flip in vertically' },
  { value: 'swing',      icon: '〰',   desc: 'Swing in from top' },
  { value: 'typewriter', icon: '⌨',   desc: 'Typewriter / reveal' },
  { value: 'spiral',     icon: '🌀',  desc: 'Spiral zoom in' },
]
