// @ts-check

export const MENU_BAR_TEMPLATES = [

  // ─────────────────────────────────────────────
  // TOP – SAFARI
  // ─────────────────────────────────────────────
  {
    id: 'mb-top-safari',
    name: 'Safari Adventure',
    position: 'top',
    description: 'Warm earthy tones with mega-dropdown columns',
    style: {
      bgColor: '#2c1810',
      bgGradientEnabled: true,
      bgGradientFrom: '#3d2314',
      bgGradientTo: '#1a0d08',
      bgGradientAngle: 180,
      itemColor: '#f5e6d3',
      itemHoverBg: '#c8622a',
      itemHoverColor: '#ffffff',
      itemActiveBg: '#a04818',
      itemActiveColor: '#ffd700',
      dropdownBg: '#2c1810',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#2c1810',
      dropdownBgGradientTo: '#1a0d08',
      dropdownColor: '#f5e6d3',
      dropdownGroupColor: '#c8622a',
      dropdownItemHoverBg: 'rgba(200,98,42,0.3)',
      dropdownItemHoverColor: '#ffd700',
      dropdownBorderColor: '#c8622a',
      dropdownBorderWidth: 1,
      dropdownShadow: '0 8px 32px rgba(0,0,0,0.6)',
      dropdownAnimation: 'slide',
      barHeight: 56,
      barWidth: 220,
      itemPaddingH: 20,
      itemPaddingV: 12,
      itemGap: 4,
      fontSize: 14,
      fontFamily: 'Rajdhani, sans-serif',
      fontWeight: '600',
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
      logoText: 'SAFARI',
      logoColor: '#c8622a',
      logoFontSize: 22,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '2px solid #c8622a',
      borderTop: '',
      borderLeft: '',
      borderRight: '',
      itemUnderlineOnHover: false,
      itemUnderlineColor: '#c8622a',
      dropdownGroupFontSize: 11,
      dropdownGroupFontWeight: '700',
      dropdownGroupLetterSpacing: '0.1em',
      dropdownItemFontSize: 13,
      dropdownItemFontWeight: '400',
      dropdownPadding: 24,
      dropdownColumnGap: 32,
      dropdownMinWidth: 200,
      separatorColor: 'rgba(200,98,42,0.3)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_ts_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_ts_002', label: 'Experiences', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_ts_001', groupLabel: 'Highlights',
            items: [
              { id: 'msi_ts_001', label: 'Overview', action: 'goto', target: '' },
              { id: 'msi_ts_002', label: 'Gallery', action: 'goto', target: '' },
              { id: 'msi_ts_003', label: 'Videos', action: 'goto', target: '' },
              { id: 'msi_ts_004', label: 'Reviews', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_ts_002', groupLabel: 'Categories',
            items: [
              { id: 'msi_ts_005', label: 'Safari Tours', action: 'goto', target: '' },
              { id: 'msi_ts_006', label: 'Wildlife', action: 'goto', target: '' },
              { id: 'msi_ts_007', label: 'Lodges', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_ts_003', label: 'Tours', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_ts_003', groupLabel: 'Featured',
            items: [
              { id: 'msi_ts_008', label: 'East Africa', action: 'goto', target: '' },
              { id: 'msi_ts_009', label: 'Southern Africa', action: 'goto', target: '' },
              { id: 'msi_ts_010', label: 'Private Safari', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_ts_004', groupLabel: 'Extras',
            items: [
              { id: 'msi_ts_011', label: 'Hot Air Balloon', action: 'goto', target: '' },
              { id: 'msi_ts_012', label: 'Bush Walk', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_ts_004', label: 'Wildlife', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_ts_005', label: 'About', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_ts_006', label: 'Contact', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  // ─────────────────────────────────────────────
  // TOP – CORPORATE
  // ─────────────────────────────────────────────
  {
    id: 'mb-top-corporate',
    name: 'Corporate Suite',
    position: 'top',
    description: 'Deep navy with clean Inter typography and crisp blue accents',
    style: {
      bgColor: '#0d1b3e',
      bgGradientEnabled: false,
      bgGradientFrom: '#0d1b3e',
      bgGradientTo: '#081228',
      bgGradientAngle: 180,
      itemColor: '#e8edf5',
      itemHoverBg: '#2563eb',
      itemHoverColor: '#ffffff',
      itemActiveBg: '#1d4ed8',
      itemActiveColor: '#ffffff',
      dropdownBg: '#0d1b3e',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#0d1b3e',
      dropdownBgGradientTo: '#081228',
      dropdownColor: '#e8edf5',
      dropdownGroupColor: '#60a5fa',
      dropdownItemHoverBg: 'rgba(37,99,235,0.2)',
      dropdownItemHoverColor: '#ffffff',
      dropdownBorderColor: '#2563eb',
      dropdownBorderWidth: 1,
      dropdownShadow: '0 8px 40px rgba(0,0,0,0.5)',
      dropdownAnimation: 'slide',
      barHeight: 60,
      barWidth: 220,
      itemPaddingH: 18,
      itemPaddingV: 12,
      itemGap: 2,
      fontSize: 14,
      fontFamily: 'Inter, Roboto, sans-serif',
      fontWeight: '500',
      letterSpacing: '0.02em',
      textTransform: 'none',
      logoText: 'CORP',
      logoColor: '#60a5fa',
      logoFontSize: 20,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '1px solid #2563eb',
      borderTop: '',
      borderLeft: '',
      borderRight: '',
      itemUnderlineOnHover: true,
      itemUnderlineColor: '#2563eb',
      dropdownGroupFontSize: 11,
      dropdownGroupFontWeight: '600',
      dropdownGroupLetterSpacing: '0.08em',
      dropdownItemFontSize: 13,
      dropdownItemFontWeight: '400',
      dropdownPadding: 20,
      dropdownColumnGap: 28,
      dropdownMinWidth: 200,
      separatorColor: 'rgba(37,99,235,0.3)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_tc_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_tc_002', label: 'Services', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_tc_001', groupLabel: 'Consulting',
            items: [
              { id: 'msi_tc_001', label: 'Strategy', action: 'goto', target: '' },
              { id: 'msi_tc_002', label: 'Operations', action: 'goto', target: '' },
              { id: 'msi_tc_003', label: 'Digital Transformation', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_tc_002', groupLabel: 'Technology',
            items: [
              { id: 'msi_tc_004', label: 'Cloud Solutions', action: 'goto', target: '' },
              { id: 'msi_tc_005', label: 'Cybersecurity', action: 'goto', target: '' },
              { id: 'msi_tc_006', label: 'Data Analytics', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_tc_003', label: 'Solutions', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_tc_003', groupLabel: 'By Industry',
            items: [
              { id: 'msi_tc_007', label: 'Finance', action: 'goto', target: '' },
              { id: 'msi_tc_008', label: 'Healthcare', action: 'goto', target: '' },
              { id: 'msi_tc_009', label: 'Retail', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_tc_004', groupLabel: 'By Size',
            items: [
              { id: 'msi_tc_010', label: 'Enterprise', action: 'goto', target: '' },
              { id: 'msi_tc_011', label: 'SMB', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_tc_004', label: 'Industries', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_tc_005', label: 'Careers', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_tc_006', label: 'About', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_tc_007', label: 'Contact', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  // ─────────────────────────────────────────────
  // TOP – DARK TECH
  // ─────────────────────────────────────────────
  {
    id: 'mb-top-dark-tech',
    name: 'Dark Tech',
    position: 'top',
    description: 'Near-black with cyan neon glow — monospace and futuristic',
    style: {
      bgColor: '#0a0a0f',
      bgGradientEnabled: true,
      bgGradientFrom: '#0a0a0f',
      bgGradientTo: '#060608',
      bgGradientAngle: 180,
      itemColor: '#a0b0c0',
      itemHoverBg: 'rgba(0,212,255,0.12)',
      itemHoverColor: '#00d4ff',
      itemActiveBg: 'rgba(0,212,255,0.22)',
      itemActiveColor: '#00ffff',
      dropdownBg: '#0d0d14',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#0d0d14',
      dropdownBgGradientTo: '#06060a',
      dropdownColor: '#a0b0c0',
      dropdownGroupColor: '#00d4ff',
      dropdownItemHoverBg: 'rgba(0,212,255,0.12)',
      dropdownItemHoverColor: '#00d4ff',
      dropdownBorderColor: 'rgba(0,212,255,0.4)',
      dropdownBorderWidth: 1,
      dropdownShadow: '0 8px 40px rgba(0,212,255,0.15), 0 2px 8px rgba(0,0,0,0.8)',
      dropdownAnimation: 'slide',
      barHeight: 52,
      barWidth: 220,
      itemPaddingH: 16,
      itemPaddingV: 10,
      itemGap: 0,
      fontSize: 13,
      fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
      fontWeight: '500',
      letterSpacing: '0.06em',
      textTransform: 'uppercase',
      logoText: 'DARKTECH',
      logoColor: '#00d4ff',
      logoFontSize: 18,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '1px solid rgba(0,212,255,0.4)',
      borderTop: '',
      borderLeft: '',
      borderRight: '',
      itemUnderlineOnHover: false,
      itemUnderlineColor: '#00d4ff',
      dropdownGroupFontSize: 10,
      dropdownGroupFontWeight: '700',
      dropdownGroupLetterSpacing: '0.12em',
      dropdownItemFontSize: 12,
      dropdownItemFontWeight: '400',
      dropdownPadding: 20,
      dropdownColumnGap: 28,
      dropdownMinWidth: 180,
      separatorColor: 'rgba(0,212,255,0.2)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_tdt_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_tdt_002', label: 'Products', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_tdt_001', groupLabel: 'Platform',
            items: [
              { id: 'msi_tdt_001', label: 'Core Engine', action: 'goto', target: '' },
              { id: 'msi_tdt_002', label: 'API Gateway', action: 'goto', target: '' },
              { id: 'msi_tdt_003', label: 'CLI Tools', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_tdt_002', groupLabel: 'Modules',
            items: [
              { id: 'msi_tdt_004', label: 'Auth', action: 'goto', target: '' },
              { id: 'msi_tdt_005', label: 'Storage', action: 'goto', target: '' },
              { id: 'msi_tdt_006', label: 'Events', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_tdt_003', label: 'Docs', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_tdt_003', groupLabel: 'Guides',
            items: [
              { id: 'msi_tdt_007', label: 'Quick Start', action: 'goto', target: '' },
              { id: 'msi_tdt_008', label: 'Tutorials', action: 'goto', target: '' },
              { id: 'msi_tdt_009', label: 'Reference', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_tdt_004', groupLabel: 'Support',
            items: [
              { id: 'msi_tdt_010', label: 'GitHub', action: 'goto', target: '' },
              { id: 'msi_tdt_011', label: 'Changelog', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_tdt_004', label: 'Features', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_tdt_005', label: 'Community', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_tdt_006', label: 'Blog', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  // ─────────────────────────────────────────────
  // TOP – ELEGANT
  // ─────────────────────────────────────────────
  {
    id: 'mb-top-elegant',
    name: 'Elegant Dark',
    position: 'top',
    description: 'Dark charcoal with gold accents and Playfair-style typography',
    style: {
      bgColor: '#1c1c1c',
      bgGradientEnabled: true,
      bgGradientFrom: '#222222',
      bgGradientTo: '#141414',
      bgGradientAngle: 180,
      itemColor: '#d4c9b4',
      itemHoverBg: 'rgba(212,175,55,0.12)',
      itemHoverColor: '#d4af37',
      itemActiveBg: 'rgba(212,175,55,0.22)',
      itemActiveColor: '#e8c84a',
      dropdownBg: '#1c1c1c',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#222222',
      dropdownBgGradientTo: '#141414',
      dropdownColor: '#d4c9b4',
      dropdownGroupColor: '#d4af37',
      dropdownItemHoverBg: 'rgba(212,175,55,0.1)',
      dropdownItemHoverColor: '#d4af37',
      dropdownBorderColor: 'rgba(212,175,55,0.4)',
      dropdownBorderWidth: 1,
      dropdownShadow: '0 12px 48px rgba(0,0,0,0.7)',
      dropdownAnimation: 'slide',
      barHeight: 64,
      barWidth: 220,
      itemPaddingH: 22,
      itemPaddingV: 14,
      itemGap: 8,
      fontSize: 14,
      fontFamily: "'Playfair Display', 'Georgia', serif",
      fontWeight: '600',
      letterSpacing: '0.04em',
      textTransform: 'none',
      logoText: 'ÉLÉGANT',
      logoColor: '#d4af37',
      logoFontSize: 20,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '1px solid rgba(212,175,55,0.5)',
      borderTop: '',
      borderLeft: '',
      borderRight: '',
      itemUnderlineOnHover: true,
      itemUnderlineColor: '#d4af37',
      dropdownGroupFontSize: 10,
      dropdownGroupFontWeight: '700',
      dropdownGroupLetterSpacing: '0.12em',
      dropdownItemFontSize: 13,
      dropdownItemFontWeight: '400',
      dropdownPadding: 28,
      dropdownColumnGap: 36,
      dropdownMinWidth: 200,
      separatorColor: 'rgba(212,175,55,0.2)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_te_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_te_002', label: 'Collection', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_te_001', groupLabel: 'Curated',
            items: [
              { id: 'msi_te_001', label: 'New Arrivals', action: 'goto', target: '' },
              { id: 'msi_te_002', label: 'Signature Series', action: 'goto', target: '' },
              { id: 'msi_te_003', label: 'Limited Edition', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_te_002', groupLabel: 'Archive',
            items: [
              { id: 'msi_te_004', label: 'Heritage Pieces', action: 'goto', target: '' },
              { id: 'msi_te_005', label: 'Past Seasons', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_te_003', label: 'Gallery', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_te_003', groupLabel: 'Visual',
            items: [
              { id: 'msi_te_006', label: 'Photography', action: 'goto', target: '' },
              { id: 'msi_te_007', label: 'Film', action: 'goto', target: '' },
              { id: 'msi_te_008', label: 'Behind the Scenes', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_te_004', label: 'Bespoke', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_te_005', label: 'About', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_te_006', label: 'Contact', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  // ─────────────────────────────────────────────
  // TOP – NATURAL
  // ─────────────────────────────────────────────
  {
    id: 'mb-top-natural',
    name: 'Natural Forest',
    position: 'top',
    description: 'Forest greens and warm cream tones evoking the outdoors',
    style: {
      bgColor: '#1a2e1a',
      bgGradientEnabled: true,
      bgGradientFrom: '#1e3320',
      bgGradientTo: '#142314',
      bgGradientAngle: 180,
      itemColor: '#f0ead6',
      itemHoverBg: '#4a7c3f',
      itemHoverColor: '#ffffff',
      itemActiveBg: '#3a6230',
      itemActiveColor: '#e8f5e0',
      dropdownBg: '#1a2e1a',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#1e3320',
      dropdownBgGradientTo: '#142314',
      dropdownColor: '#f0ead6',
      dropdownGroupColor: '#7cb87a',
      dropdownItemHoverBg: 'rgba(74,124,63,0.3)',
      dropdownItemHoverColor: '#e8f5e0',
      dropdownBorderColor: '#4a7c3f',
      dropdownBorderWidth: 1,
      dropdownShadow: '0 8px 32px rgba(0,0,0,0.5)',
      dropdownAnimation: 'slide',
      barHeight: 58,
      barWidth: 220,
      itemPaddingH: 18,
      itemPaddingV: 12,
      itemGap: 4,
      fontSize: 14,
      fontFamily: "'Lato', 'Source Sans Pro', sans-serif",
      fontWeight: '600',
      letterSpacing: '0.03em',
      textTransform: 'none',
      logoText: 'NATURA',
      logoColor: '#7cb87a',
      logoFontSize: 20,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '2px solid #4a7c3f',
      borderTop: '',
      borderLeft: '',
      borderRight: '',
      itemUnderlineOnHover: false,
      itemUnderlineColor: '#7cb87a',
      dropdownGroupFontSize: 11,
      dropdownGroupFontWeight: '700',
      dropdownGroupLetterSpacing: '0.08em',
      dropdownItemFontSize: 13,
      dropdownItemFontWeight: '400',
      dropdownPadding: 24,
      dropdownColumnGap: 28,
      dropdownMinWidth: 180,
      separatorColor: 'rgba(74,124,63,0.3)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_tn_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_tn_002', label: 'Explore', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_tn_001', groupLabel: 'Trails',
            items: [
              { id: 'msi_tn_001', label: 'Forest Walks', action: 'goto', target: '' },
              { id: 'msi_tn_002', label: 'Mountain Paths', action: 'goto', target: '' },
              { id: 'msi_tn_003', label: 'Coastal Routes', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_tn_002', groupLabel: 'Activities',
            items: [
              { id: 'msi_tn_004', label: 'Birdwatching', action: 'goto', target: '' },
              { id: 'msi_tn_005', label: 'Camping', action: 'goto', target: '' },
              { id: 'msi_tn_006', label: 'Photography', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_tn_003', label: 'Seasons', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_tn_003', groupLabel: 'Year Round',
            items: [
              { id: 'msi_tn_007', label: 'Spring Bloom', action: 'goto', target: '' },
              { id: 'msi_tn_008', label: 'Summer Trails', action: 'goto', target: '' },
              { id: 'msi_tn_009', label: 'Autumn Colours', action: 'goto', target: '' },
              { id: 'msi_tn_010', label: 'Winter Wonders', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_tn_004', label: 'Conservation', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_tn_005', label: 'Shop', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_tn_006', label: 'Contact', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  // ═════════════════════════════════════════════
  // BOTTOM TEMPLATES
  // ═════════════════════════════════════════════

  {
    id: 'mb-bottom-safari',
    name: 'Safari Adventure (Bottom)',
    position: 'bottom',
    description: 'Earthy safari tones anchored at the bottom with slide-up dropdowns',
    style: {
      bgColor: '#2c1810',
      bgGradientEnabled: true,
      bgGradientFrom: '#1a0d08',
      bgGradientTo: '#3d2314',
      bgGradientAngle: 0,
      itemColor: '#f5e6d3',
      itemHoverBg: '#c8622a',
      itemHoverColor: '#ffffff',
      itemActiveBg: '#a04818',
      itemActiveColor: '#ffd700',
      dropdownBg: '#2c1810',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#2c1810',
      dropdownBgGradientTo: '#1a0d08',
      dropdownColor: '#f5e6d3',
      dropdownGroupColor: '#c8622a',
      dropdownItemHoverBg: 'rgba(200,98,42,0.3)',
      dropdownItemHoverColor: '#ffd700',
      dropdownBorderColor: '#c8622a',
      dropdownBorderWidth: 1,
      dropdownShadow: '0 -8px 32px rgba(0,0,0,0.6)',
      dropdownAnimation: 'slide-up',
      barHeight: 56,
      barWidth: 220,
      itemPaddingH: 20,
      itemPaddingV: 12,
      itemGap: 4,
      fontSize: 14,
      fontFamily: 'Rajdhani, sans-serif',
      fontWeight: '600',
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
      logoText: 'SAFARI',
      logoColor: '#c8622a',
      logoFontSize: 22,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '',
      borderTop: '2px solid #c8622a',
      borderLeft: '',
      borderRight: '',
      itemUnderlineOnHover: false,
      itemUnderlineColor: '#c8622a',
      dropdownGroupFontSize: 11,
      dropdownGroupFontWeight: '700',
      dropdownGroupLetterSpacing: '0.1em',
      dropdownItemFontSize: 13,
      dropdownItemFontWeight: '400',
      dropdownPadding: 24,
      dropdownColumnGap: 32,
      dropdownMinWidth: 200,
      separatorColor: 'rgba(200,98,42,0.3)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_bs_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_bs_002', label: 'Experiences', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_bs_001', groupLabel: 'Highlights',
            items: [
              { id: 'msi_bs_001', label: 'Overview', action: 'goto', target: '' },
              { id: 'msi_bs_002', label: 'Gallery', action: 'goto', target: '' },
              { id: 'msi_bs_003', label: 'Reviews', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_bs_002', groupLabel: 'Categories',
            items: [
              { id: 'msi_bs_004', label: 'Safari Tours', action: 'goto', target: '' },
              { id: 'msi_bs_005', label: 'Wildlife', action: 'goto', target: '' },
              { id: 'msi_bs_006', label: 'Lodges', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_bs_003', label: 'Tours', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_bs_003', groupLabel: 'Destinations',
            items: [
              { id: 'msi_bs_007', label: 'East Africa', action: 'goto', target: '' },
              { id: 'msi_bs_008', label: 'Southern Africa', action: 'goto', target: '' },
              { id: 'msi_bs_009', label: 'Private Safari', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_bs_004', label: 'Wildlife', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_bs_005', label: 'About', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_bs_006', label: 'Contact', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  {
    id: 'mb-bottom-corporate',
    name: 'Corporate Suite (Bottom)',
    position: 'bottom',
    description: 'Navy corporate bar at the bottom with slide-up mega-menu',
    style: {
      bgColor: '#0d1b3e',
      bgGradientEnabled: false,
      bgGradientFrom: '#081228',
      bgGradientTo: '#0d1b3e',
      bgGradientAngle: 0,
      itemColor: '#e8edf5',
      itemHoverBg: '#2563eb',
      itemHoverColor: '#ffffff',
      itemActiveBg: '#1d4ed8',
      itemActiveColor: '#ffffff',
      dropdownBg: '#0d1b3e',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#0d1b3e',
      dropdownBgGradientTo: '#081228',
      dropdownColor: '#e8edf5',
      dropdownGroupColor: '#60a5fa',
      dropdownItemHoverBg: 'rgba(37,99,235,0.2)',
      dropdownItemHoverColor: '#ffffff',
      dropdownBorderColor: '#2563eb',
      dropdownBorderWidth: 1,
      dropdownShadow: '0 -8px 40px rgba(0,0,0,0.5)',
      dropdownAnimation: 'slide-up',
      barHeight: 60,
      barWidth: 220,
      itemPaddingH: 18,
      itemPaddingV: 12,
      itemGap: 2,
      fontSize: 14,
      fontFamily: 'Inter, Roboto, sans-serif',
      fontWeight: '500',
      letterSpacing: '0.02em',
      textTransform: 'none',
      logoText: 'CORP',
      logoColor: '#60a5fa',
      logoFontSize: 20,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '',
      borderTop: '1px solid #2563eb',
      borderLeft: '',
      borderRight: '',
      itemUnderlineOnHover: true,
      itemUnderlineColor: '#2563eb',
      dropdownGroupFontSize: 11,
      dropdownGroupFontWeight: '600',
      dropdownGroupLetterSpacing: '0.08em',
      dropdownItemFontSize: 13,
      dropdownItemFontWeight: '400',
      dropdownPadding: 20,
      dropdownColumnGap: 28,
      dropdownMinWidth: 200,
      separatorColor: 'rgba(37,99,235,0.3)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_bc_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_bc_002', label: 'Services', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_bc_001', groupLabel: 'Consulting',
            items: [
              { id: 'msi_bc_001', label: 'Strategy', action: 'goto', target: '' },
              { id: 'msi_bc_002', label: 'Operations', action: 'goto', target: '' },
              { id: 'msi_bc_003', label: 'Transformation', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_bc_002', groupLabel: 'Technology',
            items: [
              { id: 'msi_bc_004', label: 'Cloud', action: 'goto', target: '' },
              { id: 'msi_bc_005', label: 'Security', action: 'goto', target: '' },
              { id: 'msi_bc_006', label: 'Analytics', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_bc_003', label: 'Solutions', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_bc_003', groupLabel: 'Industries',
            items: [
              { id: 'msi_bc_007', label: 'Finance', action: 'goto', target: '' },
              { id: 'msi_bc_008', label: 'Healthcare', action: 'goto', target: '' },
              { id: 'msi_bc_009', label: 'Retail', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_bc_004', label: 'Industries', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_bc_005', label: 'Careers', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_bc_006', label: 'Contact', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  {
    id: 'mb-bottom-dark-tech',
    name: 'Dark Tech (Bottom)',
    position: 'bottom',
    description: 'Neon-cyan terminal aesthetic pinned to the bottom',
    style: {
      bgColor: '#0a0a0f',
      bgGradientEnabled: true,
      bgGradientFrom: '#060608',
      bgGradientTo: '#0a0a0f',
      bgGradientAngle: 0,
      itemColor: '#a0b0c0',
      itemHoverBg: 'rgba(0,212,255,0.12)',
      itemHoverColor: '#00d4ff',
      itemActiveBg: 'rgba(0,212,255,0.22)',
      itemActiveColor: '#00ffff',
      dropdownBg: '#0d0d14',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#06060a',
      dropdownBgGradientTo: '#0d0d14',
      dropdownColor: '#a0b0c0',
      dropdownGroupColor: '#00d4ff',
      dropdownItemHoverBg: 'rgba(0,212,255,0.12)',
      dropdownItemHoverColor: '#00d4ff',
      dropdownBorderColor: 'rgba(0,212,255,0.4)',
      dropdownBorderWidth: 1,
      dropdownShadow: '0 -8px 40px rgba(0,212,255,0.15), 0 -2px 8px rgba(0,0,0,0.8)',
      dropdownAnimation: 'slide-up',
      barHeight: 52,
      barWidth: 220,
      itemPaddingH: 16,
      itemPaddingV: 10,
      itemGap: 0,
      fontSize: 13,
      fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
      fontWeight: '500',
      letterSpacing: '0.06em',
      textTransform: 'uppercase',
      logoText: 'DARKTECH',
      logoColor: '#00d4ff',
      logoFontSize: 18,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '',
      borderTop: '1px solid rgba(0,212,255,0.4)',
      borderLeft: '',
      borderRight: '',
      itemUnderlineOnHover: false,
      itemUnderlineColor: '#00d4ff',
      dropdownGroupFontSize: 10,
      dropdownGroupFontWeight: '700',
      dropdownGroupLetterSpacing: '0.12em',
      dropdownItemFontSize: 12,
      dropdownItemFontWeight: '400',
      dropdownPadding: 20,
      dropdownColumnGap: 28,
      dropdownMinWidth: 180,
      separatorColor: 'rgba(0,212,255,0.2)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_bdt_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_bdt_002', label: 'Products', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_bdt_001', groupLabel: 'Platform',
            items: [
              { id: 'msi_bdt_001', label: 'Core Engine', action: 'goto', target: '' },
              { id: 'msi_bdt_002', label: 'API Gateway', action: 'goto', target: '' },
              { id: 'msi_bdt_003', label: 'CLI Tools', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_bdt_002', groupLabel: 'Modules',
            items: [
              { id: 'msi_bdt_004', label: 'Auth', action: 'goto', target: '' },
              { id: 'msi_bdt_005', label: 'Storage', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_bdt_003', label: 'Docs', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_bdt_003', groupLabel: 'Guides',
            items: [
              { id: 'msi_bdt_006', label: 'Quick Start', action: 'goto', target: '' },
              { id: 'msi_bdt_007', label: 'Reference', action: 'goto', target: '' },
              { id: 'msi_bdt_008', label: 'Changelog', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_bdt_004', label: 'Features', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_bdt_005', label: 'Community', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_bdt_006', label: 'Contact', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  {
    id: 'mb-bottom-elegant',
    name: 'Elegant Dark (Bottom)',
    position: 'bottom',
    description: 'Luxurious charcoal and gold bar at the base of the canvas',
    style: {
      bgColor: '#1c1c1c',
      bgGradientEnabled: true,
      bgGradientFrom: '#141414',
      bgGradientTo: '#222222',
      bgGradientAngle: 0,
      itemColor: '#d4c9b4',
      itemHoverBg: 'rgba(212,175,55,0.12)',
      itemHoverColor: '#d4af37',
      itemActiveBg: 'rgba(212,175,55,0.22)',
      itemActiveColor: '#e8c84a',
      dropdownBg: '#1c1c1c',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#141414',
      dropdownBgGradientTo: '#222222',
      dropdownColor: '#d4c9b4',
      dropdownGroupColor: '#d4af37',
      dropdownItemHoverBg: 'rgba(212,175,55,0.1)',
      dropdownItemHoverColor: '#d4af37',
      dropdownBorderColor: 'rgba(212,175,55,0.4)',
      dropdownBorderWidth: 1,
      dropdownShadow: '0 -12px 48px rgba(0,0,0,0.7)',
      dropdownAnimation: 'slide-up',
      barHeight: 64,
      barWidth: 220,
      itemPaddingH: 22,
      itemPaddingV: 14,
      itemGap: 8,
      fontSize: 14,
      fontFamily: "'Playfair Display', 'Georgia', serif",
      fontWeight: '600',
      letterSpacing: '0.04em',
      textTransform: 'none',
      logoText: 'ÉLÉGANT',
      logoColor: '#d4af37',
      logoFontSize: 20,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '',
      borderTop: '1px solid rgba(212,175,55,0.5)',
      borderLeft: '',
      borderRight: '',
      itemUnderlineOnHover: true,
      itemUnderlineColor: '#d4af37',
      dropdownGroupFontSize: 10,
      dropdownGroupFontWeight: '700',
      dropdownGroupLetterSpacing: '0.12em',
      dropdownItemFontSize: 13,
      dropdownItemFontWeight: '400',
      dropdownPadding: 28,
      dropdownColumnGap: 36,
      dropdownMinWidth: 200,
      separatorColor: 'rgba(212,175,55,0.2)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_be_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_be_002', label: 'Collection', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_be_001', groupLabel: 'Curated',
            items: [
              { id: 'msi_be_001', label: 'New Arrivals', action: 'goto', target: '' },
              { id: 'msi_be_002', label: 'Signature Series', action: 'goto', target: '' },
              { id: 'msi_be_003', label: 'Limited Edition', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_be_002', groupLabel: 'Archive',
            items: [
              { id: 'msi_be_004', label: 'Heritage Pieces', action: 'goto', target: '' },
              { id: 'msi_be_005', label: 'Past Seasons', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_be_003', label: 'Gallery', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_be_003', groupLabel: 'Visual',
            items: [
              { id: 'msi_be_006', label: 'Photography', action: 'goto', target: '' },
              { id: 'msi_be_007', label: 'Film', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_be_004', label: 'Bespoke', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_be_005', label: 'About', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_be_006', label: 'Contact', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  {
    id: 'mb-bottom-natural',
    name: 'Natural Forest (Bottom)',
    position: 'bottom',
    description: 'Earthy green tones anchored at the bottom with organic feel',
    style: {
      bgColor: '#1a2e1a',
      bgGradientEnabled: true,
      bgGradientFrom: '#142314',
      bgGradientTo: '#1e3320',
      bgGradientAngle: 0,
      itemColor: '#f0ead6',
      itemHoverBg: '#4a7c3f',
      itemHoverColor: '#ffffff',
      itemActiveBg: '#3a6230',
      itemActiveColor: '#e8f5e0',
      dropdownBg: '#1a2e1a',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#142314',
      dropdownBgGradientTo: '#1e3320',
      dropdownColor: '#f0ead6',
      dropdownGroupColor: '#7cb87a',
      dropdownItemHoverBg: 'rgba(74,124,63,0.3)',
      dropdownItemHoverColor: '#e8f5e0',
      dropdownBorderColor: '#4a7c3f',
      dropdownBorderWidth: 1,
      dropdownShadow: '0 -8px 32px rgba(0,0,0,0.5)',
      dropdownAnimation: 'slide-up',
      barHeight: 58,
      barWidth: 220,
      itemPaddingH: 18,
      itemPaddingV: 12,
      itemGap: 4,
      fontSize: 14,
      fontFamily: "'Lato', 'Source Sans Pro', sans-serif",
      fontWeight: '600',
      letterSpacing: '0.03em',
      textTransform: 'none',
      logoText: 'NATURA',
      logoColor: '#7cb87a',
      logoFontSize: 20,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '',
      borderTop: '2px solid #4a7c3f',
      borderLeft: '',
      borderRight: '',
      itemUnderlineOnHover: false,
      itemUnderlineColor: '#7cb87a',
      dropdownGroupFontSize: 11,
      dropdownGroupFontWeight: '700',
      dropdownGroupLetterSpacing: '0.08em',
      dropdownItemFontSize: 13,
      dropdownItemFontWeight: '400',
      dropdownPadding: 24,
      dropdownColumnGap: 28,
      dropdownMinWidth: 180,
      separatorColor: 'rgba(74,124,63,0.3)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_bn_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_bn_002', label: 'Explore', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_bn_001', groupLabel: 'Trails',
            items: [
              { id: 'msi_bn_001', label: 'Forest Walks', action: 'goto', target: '' },
              { id: 'msi_bn_002', label: 'Mountain Paths', action: 'goto', target: '' },
              { id: 'msi_bn_003', label: 'Coastal Routes', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_bn_002', groupLabel: 'Activities',
            items: [
              { id: 'msi_bn_004', label: 'Birdwatching', action: 'goto', target: '' },
              { id: 'msi_bn_005', label: 'Camping', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_bn_003', label: 'Seasons', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_bn_003', groupLabel: 'Year Round',
            items: [
              { id: 'msi_bn_006', label: 'Spring', action: 'goto', target: '' },
              { id: 'msi_bn_007', label: 'Summer', action: 'goto', target: '' },
              { id: 'msi_bn_008', label: 'Autumn', action: 'goto', target: '' },
              { id: 'msi_bn_009', label: 'Winter', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_bn_004', label: 'Conservation', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_bn_005', label: 'Shop', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_bn_006', label: 'Contact', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  // ═════════════════════════════════════════════
  // LEFT TEMPLATES
  // ═════════════════════════════════════════════

  {
    id: 'mb-left-safari',
    name: 'Safari Adventure (Left)',
    position: 'left',
    description: 'Vertical earthy safari sidebar with right-sliding dropdowns',
    style: {
      bgColor: '#2c1810',
      bgGradientEnabled: true,
      bgGradientFrom: '#3d2314',
      bgGradientTo: '#1a0d08',
      bgGradientAngle: 90,
      itemColor: '#f5e6d3',
      itemHoverBg: '#c8622a',
      itemHoverColor: '#ffffff',
      itemActiveBg: '#a04818',
      itemActiveColor: '#ffd700',
      dropdownBg: '#2c1810',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#2c1810',
      dropdownBgGradientTo: '#1a0d08',
      dropdownColor: '#f5e6d3',
      dropdownGroupColor: '#c8622a',
      dropdownItemHoverBg: 'rgba(200,98,42,0.3)',
      dropdownItemHoverColor: '#ffd700',
      dropdownBorderColor: '#c8622a',
      dropdownBorderWidth: 1,
      dropdownShadow: '8px 0 32px rgba(0,0,0,0.6)',
      dropdownAnimation: 'slide-right',
      barHeight: 56,
      barWidth: 220,
      itemPaddingH: 20,
      itemPaddingV: 14,
      itemGap: 2,
      fontSize: 14,
      fontFamily: 'Rajdhani, sans-serif',
      fontWeight: '600',
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
      logoText: 'SAFARI',
      logoColor: '#c8622a',
      logoFontSize: 20,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '',
      borderTop: '',
      borderLeft: '',
      borderRight: '2px solid #c8622a',
      itemUnderlineOnHover: false,
      itemUnderlineColor: '#c8622a',
      dropdownGroupFontSize: 11,
      dropdownGroupFontWeight: '700',
      dropdownGroupLetterSpacing: '0.1em',
      dropdownItemFontSize: 13,
      dropdownItemFontWeight: '400',
      dropdownPadding: 20,
      dropdownColumnGap: 24,
      dropdownMinWidth: 200,
      separatorColor: 'rgba(200,98,42,0.3)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_ls_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_ls_002', label: 'Experiences', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_ls_001', groupLabel: 'Highlights',
            items: [
              { id: 'msi_ls_001', label: 'Overview', action: 'goto', target: '' },
              { id: 'msi_ls_002', label: 'Gallery', action: 'goto', target: '' },
              { id: 'msi_ls_003', label: 'Reviews', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_ls_002', groupLabel: 'Categories',
            items: [
              { id: 'msi_ls_004', label: 'Safari Tours', action: 'goto', target: '' },
              { id: 'msi_ls_005', label: 'Wildlife', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_ls_003', label: 'Tours', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_ls_003', groupLabel: 'Destinations',
            items: [
              { id: 'msi_ls_006', label: 'East Africa', action: 'goto', target: '' },
              { id: 'msi_ls_007', label: 'Southern Africa', action: 'goto', target: '' },
              { id: 'msi_ls_008', label: 'Private Safari', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_ls_004', label: 'Wildlife', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_ls_005', label: 'About', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_ls_006', label: 'Contact', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  {
    id: 'mb-left-corporate',
    name: 'Corporate Suite (Left)',
    position: 'left',
    description: 'Clean navy vertical sidebar for corporate navigation',
    style: {
      bgColor: '#0d1b3e',
      bgGradientEnabled: false,
      bgGradientFrom: '#0d1b3e',
      bgGradientTo: '#081228',
      bgGradientAngle: 90,
      itemColor: '#e8edf5',
      itemHoverBg: '#2563eb',
      itemHoverColor: '#ffffff',
      itemActiveBg: '#1d4ed8',
      itemActiveColor: '#ffffff',
      dropdownBg: '#0d1b3e',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#0d1b3e',
      dropdownBgGradientTo: '#081228',
      dropdownColor: '#e8edf5',
      dropdownGroupColor: '#60a5fa',
      dropdownItemHoverBg: 'rgba(37,99,235,0.2)',
      dropdownItemHoverColor: '#ffffff',
      dropdownBorderColor: '#2563eb',
      dropdownBorderWidth: 1,
      dropdownShadow: '8px 0 40px rgba(0,0,0,0.5)',
      dropdownAnimation: 'slide-right',
      barHeight: 60,
      barWidth: 230,
      itemPaddingH: 20,
      itemPaddingV: 14,
      itemGap: 2,
      fontSize: 14,
      fontFamily: 'Inter, Roboto, sans-serif',
      fontWeight: '500',
      letterSpacing: '0.02em',
      textTransform: 'none',
      logoText: 'CORP',
      logoColor: '#60a5fa',
      logoFontSize: 20,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '',
      borderTop: '',
      borderLeft: '',
      borderRight: '1px solid #2563eb',
      itemUnderlineOnHover: false,
      itemUnderlineColor: '#2563eb',
      dropdownGroupFontSize: 11,
      dropdownGroupFontWeight: '600',
      dropdownGroupLetterSpacing: '0.08em',
      dropdownItemFontSize: 13,
      dropdownItemFontWeight: '400',
      dropdownPadding: 20,
      dropdownColumnGap: 24,
      dropdownMinWidth: 200,
      separatorColor: 'rgba(37,99,235,0.3)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_lc_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_lc_002', label: 'Services', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_lc_001', groupLabel: 'Consulting',
            items: [
              { id: 'msi_lc_001', label: 'Strategy', action: 'goto', target: '' },
              { id: 'msi_lc_002', label: 'Operations', action: 'goto', target: '' },
              { id: 'msi_lc_003', label: 'Transformation', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_lc_002', groupLabel: 'Technology',
            items: [
              { id: 'msi_lc_004', label: 'Cloud', action: 'goto', target: '' },
              { id: 'msi_lc_005', label: 'Security', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_lc_003', label: 'Solutions', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_lc_003', groupLabel: 'Industries',
            items: [
              { id: 'msi_lc_006', label: 'Finance', action: 'goto', target: '' },
              { id: 'msi_lc_007', label: 'Healthcare', action: 'goto', target: '' },
              { id: 'msi_lc_008', label: 'Retail', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_lc_004', label: 'Industries', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_lc_005', label: 'Careers', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_lc_006', label: 'Contact', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  {
    id: 'mb-left-dark-tech',
    name: 'Dark Tech (Left)',
    position: 'left',
    description: 'Monochrome terminal sidebar with cyan highlights sliding right',
    style: {
      bgColor: '#0a0a0f',
      bgGradientEnabled: true,
      bgGradientFrom: '#0a0a0f',
      bgGradientTo: '#040406',
      bgGradientAngle: 90,
      itemColor: '#a0b0c0',
      itemHoverBg: 'rgba(0,212,255,0.12)',
      itemHoverColor: '#00d4ff',
      itemActiveBg: 'rgba(0,212,255,0.22)',
      itemActiveColor: '#00ffff',
      dropdownBg: '#0d0d14',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#0d0d14',
      dropdownBgGradientTo: '#06060a',
      dropdownColor: '#a0b0c0',
      dropdownGroupColor: '#00d4ff',
      dropdownItemHoverBg: 'rgba(0,212,255,0.12)',
      dropdownItemHoverColor: '#00d4ff',
      dropdownBorderColor: 'rgba(0,212,255,0.4)',
      dropdownBorderWidth: 1,
      dropdownShadow: '8px 0 40px rgba(0,212,255,0.15)',
      dropdownAnimation: 'slide-right',
      barHeight: 52,
      barWidth: 220,
      itemPaddingH: 18,
      itemPaddingV: 12,
      itemGap: 0,
      fontSize: 12,
      fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
      fontWeight: '500',
      letterSpacing: '0.06em',
      textTransform: 'uppercase',
      logoText: 'SYS',
      logoColor: '#00d4ff',
      logoFontSize: 16,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '',
      borderTop: '',
      borderLeft: '',
      borderRight: '1px solid rgba(0,212,255,0.4)',
      itemUnderlineOnHover: false,
      itemUnderlineColor: '#00d4ff',
      dropdownGroupFontSize: 10,
      dropdownGroupFontWeight: '700',
      dropdownGroupLetterSpacing: '0.12em',
      dropdownItemFontSize: 12,
      dropdownItemFontWeight: '400',
      dropdownPadding: 20,
      dropdownColumnGap: 24,
      dropdownMinWidth: 180,
      separatorColor: 'rgba(0,212,255,0.2)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_ldt_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_ldt_002', label: 'Products', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_ldt_001', groupLabel: 'Platform',
            items: [
              { id: 'msi_ldt_001', label: 'Core Engine', action: 'goto', target: '' },
              { id: 'msi_ldt_002', label: 'API Gateway', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_ldt_002', groupLabel: 'Modules',
            items: [
              { id: 'msi_ldt_003', label: 'Auth', action: 'goto', target: '' },
              { id: 'msi_ldt_004', label: 'Storage', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_ldt_003', label: 'Docs', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_ldt_003', groupLabel: 'Guides',
            items: [
              { id: 'msi_ldt_005', label: 'Quick Start', action: 'goto', target: '' },
              { id: 'msi_ldt_006', label: 'Reference', action: 'goto', target: '' },
              { id: 'msi_ldt_007', label: 'Changelog', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_ldt_004', label: 'Features', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_ldt_005', label: 'Community', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  {
    id: 'mb-left-elegant',
    name: 'Elegant Dark (Left)',
    position: 'left',
    description: 'Charcoal and gold vertical sidebar with refined serif typography',
    style: {
      bgColor: '#1c1c1c',
      bgGradientEnabled: true,
      bgGradientFrom: '#222222',
      bgGradientTo: '#141414',
      bgGradientAngle: 90,
      itemColor: '#d4c9b4',
      itemHoverBg: 'rgba(212,175,55,0.12)',
      itemHoverColor: '#d4af37',
      itemActiveBg: 'rgba(212,175,55,0.22)',
      itemActiveColor: '#e8c84a',
      dropdownBg: '#1c1c1c',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#222222',
      dropdownBgGradientTo: '#141414',
      dropdownColor: '#d4c9b4',
      dropdownGroupColor: '#d4af37',
      dropdownItemHoverBg: 'rgba(212,175,55,0.1)',
      dropdownItemHoverColor: '#d4af37',
      dropdownBorderColor: 'rgba(212,175,55,0.4)',
      dropdownBorderWidth: 1,
      dropdownShadow: '8px 0 48px rgba(0,0,0,0.7)',
      dropdownAnimation: 'slide-right',
      barHeight: 64,
      barWidth: 230,
      itemPaddingH: 22,
      itemPaddingV: 16,
      itemGap: 4,
      fontSize: 14,
      fontFamily: "'Playfair Display', 'Georgia', serif",
      fontWeight: '600',
      letterSpacing: '0.04em',
      textTransform: 'none',
      logoText: 'ÉLÉGANT',
      logoColor: '#d4af37',
      logoFontSize: 18,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '',
      borderTop: '',
      borderLeft: '',
      borderRight: '1px solid rgba(212,175,55,0.5)',
      itemUnderlineOnHover: false,
      itemUnderlineColor: '#d4af37',
      dropdownGroupFontSize: 10,
      dropdownGroupFontWeight: '700',
      dropdownGroupLetterSpacing: '0.12em',
      dropdownItemFontSize: 13,
      dropdownItemFontWeight: '400',
      dropdownPadding: 24,
      dropdownColumnGap: 28,
      dropdownMinWidth: 200,
      separatorColor: 'rgba(212,175,55,0.2)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_le_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_le_002', label: 'Collection', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_le_001', groupLabel: 'Curated',
            items: [
              { id: 'msi_le_001', label: 'New Arrivals', action: 'goto', target: '' },
              { id: 'msi_le_002', label: 'Signature Series', action: 'goto', target: '' },
              { id: 'msi_le_003', label: 'Limited Edition', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_le_003', label: 'Gallery', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_le_002', groupLabel: 'Visual',
            items: [
              { id: 'msi_le_004', label: 'Photography', action: 'goto', target: '' },
              { id: 'msi_le_005', label: 'Film', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_le_004', label: 'Bespoke', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_le_005', label: 'About', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_le_006', label: 'Contact', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  {
    id: 'mb-left-natural',
    name: 'Natural Forest (Left)',
    position: 'left',
    description: 'Forest-green vertical nav with organic typography and slide-right panels',
    style: {
      bgColor: '#1a2e1a',
      bgGradientEnabled: true,
      bgGradientFrom: '#1e3320',
      bgGradientTo: '#142314',
      bgGradientAngle: 90,
      itemColor: '#f0ead6',
      itemHoverBg: '#4a7c3f',
      itemHoverColor: '#ffffff',
      itemActiveBg: '#3a6230',
      itemActiveColor: '#e8f5e0',
      dropdownBg: '#1a2e1a',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#1e3320',
      dropdownBgGradientTo: '#142314',
      dropdownColor: '#f0ead6',
      dropdownGroupColor: '#7cb87a',
      dropdownItemHoverBg: 'rgba(74,124,63,0.3)',
      dropdownItemHoverColor: '#e8f5e0',
      dropdownBorderColor: '#4a7c3f',
      dropdownBorderWidth: 1,
      dropdownShadow: '8px 0 32px rgba(0,0,0,0.5)',
      dropdownAnimation: 'slide-right',
      barHeight: 58,
      barWidth: 220,
      itemPaddingH: 18,
      itemPaddingV: 14,
      itemGap: 2,
      fontSize: 14,
      fontFamily: "'Lato', 'Source Sans Pro', sans-serif",
      fontWeight: '600',
      letterSpacing: '0.03em',
      textTransform: 'none',
      logoText: 'NATURA',
      logoColor: '#7cb87a',
      logoFontSize: 18,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '',
      borderTop: '',
      borderLeft: '',
      borderRight: '2px solid #4a7c3f',
      itemUnderlineOnHover: false,
      itemUnderlineColor: '#7cb87a',
      dropdownGroupFontSize: 11,
      dropdownGroupFontWeight: '700',
      dropdownGroupLetterSpacing: '0.08em',
      dropdownItemFontSize: 13,
      dropdownItemFontWeight: '400',
      dropdownPadding: 20,
      dropdownColumnGap: 24,
      dropdownMinWidth: 180,
      separatorColor: 'rgba(74,124,63,0.3)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_ln_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_ln_002', label: 'Explore', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_ln_001', groupLabel: 'Trails',
            items: [
              { id: 'msi_ln_001', label: 'Forest Walks', action: 'goto', target: '' },
              { id: 'msi_ln_002', label: 'Mountain Paths', action: 'goto', target: '' },
              { id: 'msi_ln_003', label: 'Coastal Routes', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_ln_002', groupLabel: 'Activities',
            items: [
              { id: 'msi_ln_004', label: 'Birdwatching', action: 'goto', target: '' },
              { id: 'msi_ln_005', label: 'Camping', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_ln_003', label: 'Seasons', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_ln_003', groupLabel: 'Year Round',
            items: [
              { id: 'msi_ln_006', label: 'Spring', action: 'goto', target: '' },
              { id: 'msi_ln_007', label: 'Summer', action: 'goto', target: '' },
              { id: 'msi_ln_008', label: 'Autumn', action: 'goto', target: '' },
              { id: 'msi_ln_009', label: 'Winter', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_ln_004', label: 'Conservation', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_ln_005', label: 'Shop', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  // ═════════════════════════════════════════════
  // RIGHT TEMPLATES
  // ═════════════════════════════════════════════

  {
    id: 'mb-right-safari',
    name: 'Safari Adventure (Right)',
    position: 'right',
    description: 'Earthy safari vertical sidebar pinned to the right edge',
    style: {
      bgColor: '#2c1810',
      bgGradientEnabled: true,
      bgGradientFrom: '#1a0d08',
      bgGradientTo: '#3d2314',
      bgGradientAngle: 270,
      itemColor: '#f5e6d3',
      itemHoverBg: '#c8622a',
      itemHoverColor: '#ffffff',
      itemActiveBg: '#a04818',
      itemActiveColor: '#ffd700',
      dropdownBg: '#2c1810',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#2c1810',
      dropdownBgGradientTo: '#1a0d08',
      dropdownColor: '#f5e6d3',
      dropdownGroupColor: '#c8622a',
      dropdownItemHoverBg: 'rgba(200,98,42,0.3)',
      dropdownItemHoverColor: '#ffd700',
      dropdownBorderColor: '#c8622a',
      dropdownBorderWidth: 1,
      dropdownShadow: '-8px 0 32px rgba(0,0,0,0.6)',
      dropdownAnimation: 'slide-left',
      barHeight: 56,
      barWidth: 220,
      itemPaddingH: 20,
      itemPaddingV: 14,
      itemGap: 2,
      fontSize: 14,
      fontFamily: 'Rajdhani, sans-serif',
      fontWeight: '600',
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
      logoText: 'SAFARI',
      logoColor: '#c8622a',
      logoFontSize: 20,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '',
      borderTop: '',
      borderLeft: '2px solid #c8622a',
      borderRight: '',
      itemUnderlineOnHover: false,
      itemUnderlineColor: '#c8622a',
      dropdownGroupFontSize: 11,
      dropdownGroupFontWeight: '700',
      dropdownGroupLetterSpacing: '0.1em',
      dropdownItemFontSize: 13,
      dropdownItemFontWeight: '400',
      dropdownPadding: 20,
      dropdownColumnGap: 24,
      dropdownMinWidth: 200,
      separatorColor: 'rgba(200,98,42,0.3)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_rs_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_rs_002', label: 'Experiences', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_rs_001', groupLabel: 'Highlights',
            items: [
              { id: 'msi_rs_001', label: 'Overview', action: 'goto', target: '' },
              { id: 'msi_rs_002', label: 'Gallery', action: 'goto', target: '' },
              { id: 'msi_rs_003', label: 'Reviews', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_rs_002', groupLabel: 'Categories',
            items: [
              { id: 'msi_rs_004', label: 'Safari Tours', action: 'goto', target: '' },
              { id: 'msi_rs_005', label: 'Wildlife', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_rs_003', label: 'Tours', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_rs_003', groupLabel: 'Destinations',
            items: [
              { id: 'msi_rs_006', label: 'East Africa', action: 'goto', target: '' },
              { id: 'msi_rs_007', label: 'Southern Africa', action: 'goto', target: '' },
              { id: 'msi_rs_008', label: 'Private Safari', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_rs_004', label: 'Wildlife', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_rs_005', label: 'About', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_rs_006', label: 'Contact', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  {
    id: 'mb-right-corporate',
    name: 'Corporate Suite (Right)',
    position: 'right',
    description: 'Deep navy corporate sidebar pinned to the right with left-sliding panels',
    style: {
      bgColor: '#0d1b3e',
      bgGradientEnabled: false,
      bgGradientFrom: '#0d1b3e',
      bgGradientTo: '#081228',
      bgGradientAngle: 270,
      itemColor: '#e8edf5',
      itemHoverBg: '#2563eb',
      itemHoverColor: '#ffffff',
      itemActiveBg: '#1d4ed8',
      itemActiveColor: '#ffffff',
      dropdownBg: '#0d1b3e',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#0d1b3e',
      dropdownBgGradientTo: '#081228',
      dropdownColor: '#e8edf5',
      dropdownGroupColor: '#60a5fa',
      dropdownItemHoverBg: 'rgba(37,99,235,0.2)',
      dropdownItemHoverColor: '#ffffff',
      dropdownBorderColor: '#2563eb',
      dropdownBorderWidth: 1,
      dropdownShadow: '-8px 0 40px rgba(0,0,0,0.5)',
      dropdownAnimation: 'slide-left',
      barHeight: 60,
      barWidth: 230,
      itemPaddingH: 20,
      itemPaddingV: 14,
      itemGap: 2,
      fontSize: 14,
      fontFamily: 'Inter, Roboto, sans-serif',
      fontWeight: '500',
      letterSpacing: '0.02em',
      textTransform: 'none',
      logoText: 'CORP',
      logoColor: '#60a5fa',
      logoFontSize: 20,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '',
      borderTop: '',
      borderLeft: '1px solid #2563eb',
      borderRight: '',
      itemUnderlineOnHover: false,
      itemUnderlineColor: '#2563eb',
      dropdownGroupFontSize: 11,
      dropdownGroupFontWeight: '600',
      dropdownGroupLetterSpacing: '0.08em',
      dropdownItemFontSize: 13,
      dropdownItemFontWeight: '400',
      dropdownPadding: 20,
      dropdownColumnGap: 24,
      dropdownMinWidth: 200,
      separatorColor: 'rgba(37,99,235,0.3)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_rc_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_rc_002', label: 'Services', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_rc_001', groupLabel: 'Consulting',
            items: [
              { id: 'msi_rc_001', label: 'Strategy', action: 'goto', target: '' },
              { id: 'msi_rc_002', label: 'Operations', action: 'goto', target: '' },
              { id: 'msi_rc_003', label: 'Transformation', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_rc_002', groupLabel: 'Technology',
            items: [
              { id: 'msi_rc_004', label: 'Cloud', action: 'goto', target: '' },
              { id: 'msi_rc_005', label: 'Security', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_rc_003', label: 'Solutions', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_rc_003', groupLabel: 'Industries',
            items: [
              { id: 'msi_rc_006', label: 'Finance', action: 'goto', target: '' },
              { id: 'msi_rc_007', label: 'Healthcare', action: 'goto', target: '' },
              { id: 'msi_rc_008', label: 'Retail', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_rc_004', label: 'Industries', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_rc_005', label: 'Careers', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_rc_006', label: 'Contact', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  {
    id: 'mb-right-dark-tech',
    name: 'Dark Tech (Right)',
    position: 'right',
    description: 'Cyberpunk right-side panel with neon-cyan left-sliding submenus',
    style: {
      bgColor: '#0a0a0f',
      bgGradientEnabled: true,
      bgGradientFrom: '#040406',
      bgGradientTo: '#0a0a0f',
      bgGradientAngle: 270,
      itemColor: '#a0b0c0',
      itemHoverBg: 'rgba(0,212,255,0.12)',
      itemHoverColor: '#00d4ff',
      itemActiveBg: 'rgba(0,212,255,0.22)',
      itemActiveColor: '#00ffff',
      dropdownBg: '#0d0d14',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#06060a',
      dropdownBgGradientTo: '#0d0d14',
      dropdownColor: '#a0b0c0',
      dropdownGroupColor: '#00d4ff',
      dropdownItemHoverBg: 'rgba(0,212,255,0.12)',
      dropdownItemHoverColor: '#00d4ff',
      dropdownBorderColor: 'rgba(0,212,255,0.4)',
      dropdownBorderWidth: 1,
      dropdownShadow: '-8px 0 40px rgba(0,212,255,0.15)',
      dropdownAnimation: 'slide-left',
      barHeight: 52,
      barWidth: 220,
      itemPaddingH: 18,
      itemPaddingV: 12,
      itemGap: 0,
      fontSize: 12,
      fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
      fontWeight: '500',
      letterSpacing: '0.06em',
      textTransform: 'uppercase',
      logoText: 'SYS',
      logoColor: '#00d4ff',
      logoFontSize: 16,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '',
      borderTop: '',
      borderLeft: '1px solid rgba(0,212,255,0.4)',
      borderRight: '',
      itemUnderlineOnHover: false,
      itemUnderlineColor: '#00d4ff',
      dropdownGroupFontSize: 10,
      dropdownGroupFontWeight: '700',
      dropdownGroupLetterSpacing: '0.12em',
      dropdownItemFontSize: 12,
      dropdownItemFontWeight: '400',
      dropdownPadding: 20,
      dropdownColumnGap: 24,
      dropdownMinWidth: 180,
      separatorColor: 'rgba(0,212,255,0.2)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_rdt_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_rdt_002', label: 'Products', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_rdt_001', groupLabel: 'Platform',
            items: [
              { id: 'msi_rdt_001', label: 'Core Engine', action: 'goto', target: '' },
              { id: 'msi_rdt_002', label: 'API Gateway', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_rdt_002', groupLabel: 'Modules',
            items: [
              { id: 'msi_rdt_003', label: 'Auth', action: 'goto', target: '' },
              { id: 'msi_rdt_004', label: 'Storage', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_rdt_003', label: 'Docs', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_rdt_003', groupLabel: 'Guides',
            items: [
              { id: 'msi_rdt_005', label: 'Quick Start', action: 'goto', target: '' },
              { id: 'msi_rdt_006', label: 'Reference', action: 'goto', target: '' },
              { id: 'msi_rdt_007', label: 'Changelog', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_rdt_004', label: 'Features', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_rdt_005', label: 'Community', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  {
    id: 'mb-right-elegant',
    name: 'Elegant Dark (Right)',
    position: 'right',
    description: 'Charcoal and gold right-rail sidebar with left-floating luxury menus',
    style: {
      bgColor: '#1c1c1c',
      bgGradientEnabled: true,
      bgGradientFrom: '#141414',
      bgGradientTo: '#222222',
      bgGradientAngle: 270,
      itemColor: '#d4c9b4',
      itemHoverBg: 'rgba(212,175,55,0.12)',
      itemHoverColor: '#d4af37',
      itemActiveBg: 'rgba(212,175,55,0.22)',
      itemActiveColor: '#e8c84a',
      dropdownBg: '#1c1c1c',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#141414',
      dropdownBgGradientTo: '#222222',
      dropdownColor: '#d4c9b4',
      dropdownGroupColor: '#d4af37',
      dropdownItemHoverBg: 'rgba(212,175,55,0.1)',
      dropdownItemHoverColor: '#d4af37',
      dropdownBorderColor: 'rgba(212,175,55,0.4)',
      dropdownBorderWidth: 1,
      dropdownShadow: '-8px 0 48px rgba(0,0,0,0.7)',
      dropdownAnimation: 'slide-left',
      barHeight: 64,
      barWidth: 230,
      itemPaddingH: 22,
      itemPaddingV: 16,
      itemGap: 4,
      fontSize: 14,
      fontFamily: "'Playfair Display', 'Georgia', serif",
      fontWeight: '600',
      letterSpacing: '0.04em',
      textTransform: 'none',
      logoText: 'ÉLÉGANT',
      logoColor: '#d4af37',
      logoFontSize: 18,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '',
      borderTop: '',
      borderLeft: '1px solid rgba(212,175,55,0.5)',
      borderRight: '',
      itemUnderlineOnHover: false,
      itemUnderlineColor: '#d4af37',
      dropdownGroupFontSize: 10,
      dropdownGroupFontWeight: '700',
      dropdownGroupLetterSpacing: '0.12em',
      dropdownItemFontSize: 13,
      dropdownItemFontWeight: '400',
      dropdownPadding: 24,
      dropdownColumnGap: 28,
      dropdownMinWidth: 200,
      separatorColor: 'rgba(212,175,55,0.2)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_re_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_re_002', label: 'Collection', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_re_001', groupLabel: 'Curated',
            items: [
              { id: 'msi_re_001', label: 'New Arrivals', action: 'goto', target: '' },
              { id: 'msi_re_002', label: 'Signature Series', action: 'goto', target: '' },
              { id: 'msi_re_003', label: 'Limited Edition', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_re_003', label: 'Gallery', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_re_002', groupLabel: 'Visual',
            items: [
              { id: 'msi_re_004', label: 'Photography', action: 'goto', target: '' },
              { id: 'msi_re_005', label: 'Film', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_re_004', label: 'Bespoke', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_re_005', label: 'About', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_re_006', label: 'Contact', icon: '', action: 'goto', target: '', children: [] },
    ],
  },

  {
    id: 'mb-right-natural',
    name: 'Natural Forest (Right)',
    position: 'right',
    description: 'Verdant right sidebar with organic greens and slide-left sub-panels',
    style: {
      bgColor: '#1a2e1a',
      bgGradientEnabled: true,
      bgGradientFrom: '#142314',
      bgGradientTo: '#1e3320',
      bgGradientAngle: 270,
      itemColor: '#f0ead6',
      itemHoverBg: '#4a7c3f',
      itemHoverColor: '#ffffff',
      itemActiveBg: '#3a6230',
      itemActiveColor: '#e8f5e0',
      dropdownBg: '#1a2e1a',
      dropdownBgGradientEnabled: false,
      dropdownBgGradientFrom: '#142314',
      dropdownBgGradientTo: '#1e3320',
      dropdownColor: '#f0ead6',
      dropdownGroupColor: '#7cb87a',
      dropdownItemHoverBg: 'rgba(74,124,63,0.3)',
      dropdownItemHoverColor: '#e8f5e0',
      dropdownBorderColor: '#4a7c3f',
      dropdownBorderWidth: 1,
      dropdownShadow: '-8px 0 32px rgba(0,0,0,0.5)',
      dropdownAnimation: 'slide-left',
      barHeight: 58,
      barWidth: 220,
      itemPaddingH: 18,
      itemPaddingV: 14,
      itemGap: 2,
      fontSize: 14,
      fontFamily: "'Lato', 'Source Sans Pro', sans-serif",
      fontWeight: '600',
      letterSpacing: '0.03em',
      textTransform: 'none',
      logoText: 'NATURA',
      logoColor: '#7cb87a',
      logoFontSize: 18,
      logoFontWeight: '700',
      logoImage: '',
      logoPosition: 'left',
      borderBottom: '',
      borderTop: '',
      borderLeft: '2px solid #4a7c3f',
      borderRight: '',
      itemUnderlineOnHover: false,
      itemUnderlineColor: '#7cb87a',
      dropdownGroupFontSize: 11,
      dropdownGroupFontWeight: '700',
      dropdownGroupLetterSpacing: '0.08em',
      dropdownItemFontSize: 13,
      dropdownItemFontWeight: '400',
      dropdownPadding: 20,
      dropdownColumnGap: 24,
      dropdownMinWidth: 180,
      separatorColor: 'rgba(74,124,63,0.3)',
      separatorEnabled: true,
      zIndex: 1000,
    },
    items: [
      { id: 'mi_rn_001', label: 'Home', icon: '', action: 'goto', target: '', children: [] },
      {
        id: 'mi_rn_002', label: 'Explore', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_rn_001', groupLabel: 'Trails',
            items: [
              { id: 'msi_rn_001', label: 'Forest Walks', action: 'goto', target: '' },
              { id: 'msi_rn_002', label: 'Mountain Paths', action: 'goto', target: '' },
              { id: 'msi_rn_003', label: 'Coastal Routes', action: 'goto', target: '' },
            ],
          },
          {
            id: 'mg_rn_002', groupLabel: 'Activities',
            items: [
              { id: 'msi_rn_004', label: 'Birdwatching', action: 'goto', target: '' },
              { id: 'msi_rn_005', label: 'Camping', action: 'goto', target: '' },
            ],
          },
        ],
      },
      {
        id: 'mi_rn_003', label: 'Seasons', icon: '', action: 'none', target: '',
        children: [
          {
            id: 'mg_rn_003', groupLabel: 'Year Round',
            items: [
              { id: 'msi_rn_006', label: 'Spring', action: 'goto', target: '' },
              { id: 'msi_rn_007', label: 'Summer', action: 'goto', target: '' },
              { id: 'msi_rn_008', label: 'Autumn', action: 'goto', target: '' },
              { id: 'msi_rn_009', label: 'Winter', action: 'goto', target: '' },
            ],
          },
        ],
      },
      { id: 'mi_rn_004', label: 'Conservation', icon: '', action: 'goto', target: '', children: [] },
      { id: 'mi_rn_005', label: 'Shop', icon: '', action: 'goto', target: '', children: [] },
    ],
  },
]

/**
 * Returns all templates for a given position.
 * @param {'top'|'bottom'|'left'|'right'} position
 */
export function getMenuBarTemplatesByPosition(position) {
  return MENU_BAR_TEMPLATES.filter(t => t.position === position)
}

/**
 * Returns a single template by its id, or null if not found.
 * @param {string} id
 */
export function getMenuBarTemplateById(id) {
  return MENU_BAR_TEMPLATES.find(t => t.id === id) || null
}
